### ISSUE TITLE
Status message not updated properly

### ISSUE THREAD

**Issue by haferburg** [sublimelsp/LSP#1495] opened 2020-11-28 13:15 UTC
E. g. the status message is not cleared when `textDocument/publishDiagnostics` becomes empty after I fixed all issues.

It always seems to lag behind one change:

![image](https://user-images.githubusercontent.com/4941909/100516369-b873b680-3183-11eb-8bfa-7ae5e744c850.png)

![image](https://user-images.githubusercontent.com/4941909/100516383-d04b3a80-3183-11eb-9b01-db1df63d6a08.png)

![image](https://user-images.githubusercontent.com/4941909/100516387-db9e6600-3183-11eb-809e-b815961d1ff0.png)

![image](https://user-images.githubusercontent.com/4941909/100516403-eb1daf00-3183-11eb-9145-da11728712e0.png)

The message is updated if I move the cursor to another line, then come back.
![image](https://user-images.githubusercontent.com/4941909/100516424-0ab4d780-3184-11eb-8a25-3741e8b50e1c.png)

I just updated to LSP 0.14.3.

**Comment by rwols** [comment] 2020-11-28 15:42
This is fixed in the ST4 branch. I don't personally see me fixing this in the ST3 branch, as I have been using ST4 full-time for about a year now. You can download an alpha version of ST4 through the Discord channel (see the bottom of the readme page of this repo to find the invite link). Overall, there have been a ton of both small and big improvements.

**Comment by 7mail** [comment] 2020-12-31 11:39
https://github.com/7mail/lsp_1495/blob/main/1495.log here's a log corresponding to changing a line
`const auto t = 1l;`
`const auto t = 1s;`
`const auto t = 1sv;`
`const auto t = 1s;`
in somewhat this order and saving in between.
The problem was auto format on save https://packagecontrol.io/packages/Clang%20Format
Disabling it fixes the issue.
lsp's formatting doesn't cause this issue.

**Comment by rwols** [comment] 2020-12-31 13:28
I've created a project trying to reproduce your issue, but I cannot reproduce it: https://github.com/rwols/lsp-issue-1495

I installed the Clang Format plugin. Packages/User/clang_format.sublime-settings is:

```js
{
    "style": "File",
    "format_on_save": true,
    "binary": "/usr/local/bin/clang-format",
}
```

`lsp_format_on_save` is set to `false` in Packages/User/LSP.sublime-settings.

**Comment by 7mail** [comment] 2020-12-31 19:46
@rwols Thanks for taking the time! I see that the bug doesn't show on small files.
https://github.com/7mail/lspbug/ I've invited you to see this repo. I added some gibberish files and lots of gtest macros and some clang-tidy errors too.
The bug now shows up.
i've also added my lsp settings if they're of any use.

**Comment by rwols** [comment] 2021-06-04 18:42
Closing because I cannot reproduce this.

**Comment by rwols** [comment] 2021-06-04 19:19
It’s apparently still an issue.

**Comment by rchl** [comment] 2022-10-09 11:38
I'll assume this was fixed as there were some related changes and there is no reliable reproduction steps in here.

**Closed by rchl** 2022-10-09 11:38 UTC
Labels: investigation
