### ISSUE TITLE
Is it possible to show field descriptions by default?

### ISSUE THREAD

**Issue by lua-rocks** [sublimelsp/LSP#2197] opened 2023-02-13 09:12 UTC
Hello. I'm trying to move from VSCode to SublimeText and there is one difference in your LSP that I really miss.

In VSCode, I can double-press ctrl+space to always see a detailed description of all object fields automatically.

In your implementation the field descriptions are hidden and I have to take my hands off the keyboard, then click on the "More" link, only then the description appears, and when I move to the next field it disappears again.

I would like to ALWAYS see field descriptions, without having to click the "More" link (this link I don't want to see at all).

![more](https://user-images.githubusercontent.com/82697845/218416701-30cbd0c8-a81b-47b2-910f-e28f5403fbcf.png)

**Comment by rchl** [comment] 2023-02-13 09:19
Duplicate of https://github.com/sublimelsp/LSP/issues/1421.

But you can press F12 to trigger the `More` link. It's a built ST shortcut to trigger a link in that area.

**Closed by rchl** 2023-02-13 09:19 UTC

**Comment by lua-rocks** [comment] 2023-02-13 09:26
@rchl This is not the solution. Why do I have to press f12 after every field switch? If my object has a hundred fields and I want to quickly run through all the fields with arrows, looking for something specific in their descriptions, having to extra press f12 a hundred times would make me change to a more convenient editor.

**Comment by rchl** [comment] 2023-02-13 09:30
Did you read the issue I've linked? Even I have acknowledged that it's an issue. It's just that the ST API has limitations that doesn't let us fix that outside of using some hacks that might not work fully.

The comment about F12 is just to make aware that there exists an easier way of triggering the documentation instead of reaching for the mouse.

**Comment by lua-rocks** [comment] 2023-02-13 09:32
@rchl Sorry I didn't read. Now it is clear. Thank you!
