### ISSUE TITLE
Corrupted initialize message

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [sublimelsp/LSP#1634] opened 2021-04-03 16:32 UTC
**Describe the bug**
[ZLS](https://github.com/zigtools/zls) fails to start, waiting for a `'\n'` to be sent; this suggests that LSP does not terminate the header properly or sends more bytes than specified in the header. This bug seems to occur randomly, more often when ZLS is optimized, but not while it is debugged, which suggests a concurrency-related issue. The fact that ZLS is single threaded and the control flow for reading the header is straightforward makes me fairly certain that this is a bug in Sublime-LSP.

**To Reproduce**
  * Download a build of ZLS from https://github.com/zigtools/zls/releases/tag/0.1.0 and unpack it
  * Add the executable to the LSP.sublime-settings as a new server
  * Enable the server in any project
  * When starting the server, the status bar only shows `Starting zls...` and all LSP operations stay grayed out.
  * If this does not happen on startup, it often happens after executing `LSP: Restart Servers` a few times.

**Expected behavior**
The server should start normally and all Sublime-LSP features should be available.

**Environment:**
- OS: Arch Linux, up-to-date
- Sublime Text version: 3211
- LSP version: 0.14.3
- Language servers used: ZLS

**Comment by rwols** [comment] 2021-04-04 13:57
I tried to reproduce this for ST4 at least, but release 0.1.0 has missing symbols (for macOS at least):

```
zls: dyld: Symbol not found: __tlv_bootstrap
zls:   Referenced from: /Users/raoulwols/Downloads/x86_64-macos/zls
zls:   Expected in: /Users/raoulwols/Downloads/x86_64-macos/zls
zls:  in /Users/raoulwols/Downloads/x86_64-macos/zls
```

My ST4 client configuration was

```
		"zls": {
			"command": [
				"$home/Downloads/x86_64-macos/zls"
			],
			"selector": "source.zig",
			"enabled": true
		},
```

**Comment by rwols** [comment] 2021-04-04 14:02
There's quite a bit of missing symbols:

```
~/D/x86_64-macos $ pwd
/Users/raoulwols/Downloads/x86_64-macos
~/D/x86_64-macos $ nm -u zls
__NSGetExecutablePath
___divti3
___error
___fixunsdfti
___udivti3
___umodti3
__dyld_get_image_header
__dyld_get_image_name
__dyld_get_image_vmaddr_slide
__dyld_image_count
__tlv_bootstrap
_abort
_arc4random_buf
_chdir
_clock_gettime
_close$NOCANCEL
_dup2
_environ
_execve
_exit
_fchdir
_fcntl
_fcopyfile
_flock
_fork
_fstat$INODE64
_fstatat$INODE64
_getcwd
_getenv
_isatty
_memcpy
_memmove
_memset
_mmap
_munmap
_open
_openat
_pipe
_pread
_pthread_cond_broadcast
_pthread_cond_destroy
_pthread_cond_wait
_pthread_mutex_destroy
_pthread_mutex_lock
_pthread_mutex_unlock
_read
_realpath$DARWIN_EXTSN
_renameat
_sched_yield
_sendfile
_setregid
_setreuid
_unlinkat
_waitpid
_write
dyld_stub_binder
```

**Comment by rwols** [comment] 2021-04-04 14:23
I compiled zig from HEAD with brew, and then I compiled zls. It now starts correctly. You may want to investigate the missing symbols issue further.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/2431823/113511805-09e0e780-9562-11eb-9461-03a0bb06e2c7.png">

**Comment by rwols** [comment] 2021-04-04 14:30
> this suggests that LSP does not terminate the header properly or sends more bytes than specified in the header. This bug seems to occur randomly, more often when ZLS is optimized, but not while it is debugged, which suggests a concurrency-related issue.

Since you're using ST3, and because ST4 will be released publicly this year, and since there were many changes in this package regarding stdio streams, I'd suggest either downloading a prerelease of ST4 from the Discord channel and see if the bug occurs there. Or wait for ST4 to release. I don't think we want any more fixes for ST3.

**Closed** 2021-05-28 20:58 UTC
Labels: ST3, wontfix
