### ISSUE TITLE
Lingering Micorsoft pyhton language server after ST close

### ISSUE THREAD

**Issue by Aero-fish** [sublimelsp/LSP#965] opened 2020-04-12 11:53 UTC
I found the language server is not terminated after ST is closed, and new instance of ST spawns a new instance of the language server.

I am using ST4 on windows, and I am on the st4000-exploration branch.

**Comment by ayoub-benali** [comment] 2020-04-12 15:28
Looks similar to https://github.com/sublimelsp/LSP/issues/410

**Comment by Aero-fish** [comment] 2020-04-12 19:56
Yes. There is a new API 'on_exit' in 'sublime_plugin.EventListener' in ST4. I think this is solvable now. If there is no road map for this  yet, maybe provide a window command to end all active language servers, so for those who is testing ST4 can call it on exit.

**Comment by rwols** [comment] 2020-04-13 09:51
Duplicate of #410

**Closed by rwols** 2020-04-13 09:51 UTC
