### ISSUE TITLE
Prepare for upgrade of bracex and wcmatch libraries

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#2455] opened 2024-04-20 12:43 UTC
If the dust has settled with transitioning to python 3.8, two PRs are prepared to upgrade 

- [bracex to from 2.1.1 to 2.4](https://github.com/packagecontrol/channel/pull/8)
- [wcmatch from 1.2.1 to 8.5.1](https://github.com/packagecontrol/channel/pull/7)

by shipping them directly from pypi for python 3.8

I already installed them manually and haven't seen any negative impacts so far. Maybe someone more involved could double check for possible incompatibilities, especially as version numbers of wcmatch differ significantly.

**Comment by predragnikolic** [comment] 2024-04-20 19:26
bracex is used by wcmatch
wcmatch still exposes the same API that LSP uses.
The behavior might be different however. 

Do you maybe have a guide on how to install those deps locally?

**Comment by deathaxe** [comment] 2024-04-20 21:09
You can download the whl files and directly extract them into ST's Lib/python38 folder. 

- https://pypi.org/project/bracex/#files
- https://pypi.org/project/wcmatch/#files

Make sure to remove the currently installed libraries' folders first.

**Comment by predragnikolic** [comment] 2024-05-03 08:51
I will start with testing this.

**Comment by predragnikolic** [comment] 2024-05-03 08:53
If someone want to also try to test it out.
You would need to keep the bracex-2.1.1.dist-info and wcmatch-1.2.1.dist-info 
and change the INSTALLER to not point to `Package Control`

**Comment by predragnikolic** [comment] 2024-05-20 15:48
I have't run into any issues in the past two weeks.

**Comment by predragnikolic** [comment] 2024-05-20 16:35
I will close this issue, because there are no code changes that needs to be done on the LSP side, 
and I haven't noticed any regressions.

Feel free to reopen this is you think otherwise.

**Closed by predragnikolic** 2024-05-20 16:35 UTC
