### ISSUE TITLE
typescript-language-server shuts down immediately after initializing, vscode-css raises exception

### ISSUE THREAD

**Issue by jamesWalker55** [sublimelsp/LSP#1561] opened 2021-01-27 14:42 UTC
**Describe the bug**
After installing and enabling typescript-language-server and vscode-css, I restarted Sublime Text. On startup, typescript-language-server raises the message `INFO: Could not find files for the given pattern(s)` then shuts down, vscode-css raises a TypeError `TypeError: Cannot read property 'validProperties' of null`.

At this point, vscode-css works with limited functionality, while typescript-language-server does not work at all.

**To Reproduce**
1. Install LSP through Package Control
2. Install typescript-language-server and vscode-css through npm 
3. vscode-css

**Expected behavior**
The typescript-language-server initializes successfully and doesn't shut down. vscode-css doesn't raise an error.

**Environment (please complete the following information):**
- OS: Windows 10 64-bit
- Sublime Text version: 3211
- LSP version: 0.14.3
- Language servers used: typescript-language-server, vscode-css
- Other servers installed: lsp-html, pyls, 

**Additional context**

I enabled log_stderr and log_debug, the LSP log panel shows this:

```
:: --> typescript-language-server initialize(1)
:: --> vscode-css initialize(1)
typescript-language-server: INFO: Could not find files for the given pattern(s).
:: <<< typescript-language-server 1
:: --> typescript-language-server shutdown(2)
:: <<< typescript-language-server 2
::  -> typescript-language-server exit
:: <<< vscode-css 1
::  -> vscode-css initialized
::  -> vscode-css textDocument/didOpen
:: <-- vscode-css workspace/configuration(0)
:: >>> vscode-css 0
vscode-css: Unhandled exception: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at LintConfigurationSettings.getSetting (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lintRules.js:81:29)
    at new LintVisitor (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:48:39)
    at Function.LintVisitor.entries (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:61:27)
    at CSSValidation.doValidation (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\cssValidation.js:33:60)
    at C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\cssServerMain.js:151:60
:: --> vscode-css textDocument/documentColor(2)
:: <<< vscode-css 2
```

My LSP settings look like this:

```
{
  "log_stderr": true,
  "log_debug": true,
  "clients":
  {
    "jdtls":
    {
      "command":
      [
        "java",
        "--add-modules=ALL-SYSTEM",
        "--add-opens",
        "java.base/java.util=ALL-UNNAMED",
        "--add-opens",
        "java.base/java.lang=ALL-UNNAMED",
        "-Declipse.application=org.eclipse.jdt.ls.core.id1",
        "-Dosgi.bundles.defaultStartLevel=4",
        "-Declipse.product=org.eclipse.jdt.ls.core.product",
        "-Dfile.encoding=UTF-8",
        "-DwatchParentProcess=false",
        "-noverify",
        "-Xmx1G",
        "-XX:+UseG1GC",
        "-XX:+UseStringDeduplication",
        "-jar",
        "C:/Tools/language_servers/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar",
        "-configuration",
        "C:/Tools/language_servers/jdt-language-server-latest/config_win",
        "-data",
        "C:/Users/James/AppData/Local/Temp/${project_base_name}/jdt_ws"
      ],
      "enabled": false,
      "languageId": "java",
      "scopes":
      [
        "source.java"
      ],
      "syntaxes":
      [
        "Packages/Java/Java.sublime-syntax"
      ]
    },
    "lsp-html":
    {
      "enabled": false
    }
  }
}
```

**Comment by rchl** [comment] 2021-01-27 15:16
It could be a problem with missing configuration but the LSP settings that you've listed don't even mention those server configurations that you have problems with.

You could probably avoid those problems by installing relevant helper packages: https://github.com/sublimelsp/LSP-typescript and https://github.com/sublimelsp/LSP-css

**Comment by jamesWalker55** [comment] 2021-01-27 15:56
I installed those and code completion seems to be working. However typescript-language-server still shuts down and vscode-css still raises constant errors in the log, not sure if this is any cause for conccern:

```
:: --> lsp-typescript initialize(1)
:: --> typescript-language-server initialize(1)
lsp-typescript: INFO: Could not find files for the given pattern(s).
typescript-language-server: INFO: Could not find files for the given pattern(s).
:: --> lsp-css initialize(1)
:: --> vscode-css initialize(1)
:: <<< lsp-typescript 1
::  -> lsp-typescript initialized
:: <<< typescript-language-server 1
:: --> typescript-language-server shutdown(2)
:: <<< typescript-language-server 2
::  -> typescript-language-server exit
::  -> lsp-typescript textDocument/didOpen
:: <<< lsp-css 1
::  -> lsp-css initialized
::  -> lsp-css workspace/didChangeConfiguration
::  -> lsp-css textDocument/didOpen
::  -> lsp-css textDocument/didOpen
:: <<< vscode-css 1
::  -> vscode-css initialized
::  -> vscode-css textDocument/didOpen
::  -> lsp-css textDocument/didOpen
::  -> vscode-css textDocument/didOpen
::  -> lsp-css textDocument/didOpen
:: <-- vscode-css workspace/configuration(0)
:: <-- lsp-css workspace/configuration(0)
:: >>> vscode-css 0
:: <-- vscode-css workspace/configuration(1)
:: >>> lsp-css 0
:: <-- lsp-css workspace/configuration(1)
:: >>> vscode-css 1
:: >>> lsp-css 1
vscode-css: Unhandled exception: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at LintConfigurationSettings.getSetting (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lintRules.js:81:29)
    at new LintVisitor (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:48:39)
    at Function.LintVisitor.entries (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:61:27)
    at CSSValidation.doValidation (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\cssValidation.js:33:60)
    at C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\cssServerMain.js:151:60
:: <-  lsp-css textDocument/publishDiagnostics
vscode-css: Unhandled exception: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at LintConfigurationSettings.getSetting (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lintRules.js:81:29)
    at new LintVisitor (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:48:39)
    at Function.LintVisitor.entries (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:61:27)
    at CSSValidation.doValidation (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\cssValidation.js:33:60)
    at C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\cssServerMain.js:151:60
:: <-  lsp-css textDocument/publishDiagnostics
:: --> lsp-css textDocument/documentColor(2)
:: <<< lsp-css 2
:: --> lsp-css textDocument/documentColor(3)
:: <<< lsp-css 3
:: <-  lsp-typescript textDocument/publishDiagnostics
:: <-  lsp-typescript textDocument/publishDiagnostics
::  -> vscode-css textDocument/didChange
::  -> lsp-css textDocument/didChange
:: --> lsp-css textDocument/documentColor(4)
:: <<< lsp-css 4
:: <-  lsp-css textDocument/publishDiagnostics
vscode-css: Unhandled exception: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at LintConfigurationSettings.getSetting (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lintRules.js:81:29)
    at new LintVisitor (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:48:39)
    at Function.LintVisitor.entries (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:61:27)
    at CSSValidation.doValidation (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\cssValidation.js:33:60)
    at C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\cssServerMain.js:151:60
::  -> vscode-css textDocument/didChange
::  -> lsp-css textDocument/didChange
:: --> lsp-css textDocument/completion(5)
:: <<< lsp-css 5
:: <-  lsp-css textDocument/publishDiagnostics
vscode-css: Unhandled exception: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at LintConfigurationSettings.getSetting (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lintRules.js:81:29)
    at new LintVisitor (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:48:39)
    at Function.LintVisitor.entries (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:61:27)
    at CSSValidation.doValidation (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\cssValidation.js:33:60)
    at C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\cssServerMain.js:151:60
::  -> vscode-css textDocument/didChange
::  -> lsp-css textDocument/didChange
:: --> lsp-css textDocument/documentHighlight(6)
:: <<< lsp-css 6
:: --> lsp-css textDocument/documentColor(7)
:: <<< lsp-css 7
:: <-  lsp-css textDocument/publishDiagnostics
vscode-css: Unhandled exception: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at LintConfigurationSettings.getSetting (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lintRules.js:81:29)
    at new LintVisitor (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:48:39)
    at Function.LintVisitor.entries (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\lint.js:61:27)
    at CSSValidation.doValidation (C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\node_modules\vscode-css-languageservice\lib\umd\services\cssValidation.js:33:60)
    at C:\Users\James\AppData\Roaming\npm\node_modules\vscode-css-languageserver-bin\cssServerMain.js:151:60
:: --> lsp-css textDocument/hover(8)
:: <<< lsp-css 8
```

**Comment by rchl** [comment] 2021-01-27 16:04
Disable vscode-css. It's a duplicate of lsp-css.

**Closed** 2021-01-27 16:17 UTC

**Comment by rchl** [comment] 2021-01-27 20:48
> lsp-typescript: INFO: Could not find files for the given pattern(s).

I'm not sure where that message comes from as I can't see it here with LSP-typescript v1.1.5

The log would show more information if you would enable `log_payloads` LSP option. It seems like it's something in the `initialize` message payload that makes it trigger that info message.

But info messages are typically not something that one should be concerned with. ;)

**Comment by jamesWalker55** [comment] 2021-01-27 21:10
Thanks for the reassurance. Just in case, here's the initialize payload before the info message:

```
:: --> lsp-typescript initialize(1): {'processId': 38496, 'rootPath': 'D:\\Programming\\odin-project', 'clientInfo': {'version': '0.14.3', 'name': 'Sublime Text LSP'}, 'capabilities': {'workspace': {'symbol': {'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'executeCommand': {}, 'didChangeConfiguration': {'dynamicRegistration': True}, 'workspaceEdit': {'failureHandling': 'abort', 'documentChanges': True}, 'applyEdit': True, 'configuration': True, 'workspaceFolders': True}, 'experimental': {}, 'textDocument': {'publishDiagnostics': {'relatedInformation': True}, 'completion': {'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'completionItem': {'snippetSupport': True}, 'dynamicRegistration': True}, 'signatureHelp': {'dynamicRegistration': True, 'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'hover': {'contentFormat': ['markdown', 'plaintext'], 'dynamicRegistration': True}, 'declaration': {'linkSupport': True, 'dynamicRegistration': True}, 'synchronization': {'didSave': True, 'willSave': True, 'willSaveWaitUntil': True, 'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'references': {'dynamicRegistration': True}, 'formatting': {'dynamicRegistration': True}, 'documentSymbol': {'hierarchicalDocumentSymbolSupport': True, 'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'rename': {'dynamicRegistration': True}, 'implementation': {'linkSupport': True, 'dynamicRegistration': True}, 'colorProvider': {'dynamicRegistration': True}, 'definition': {'linkSupport': True, 'dynamicRegistration': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}, 'dynamicRegistration': True}, 'typeDefinition': {'linkSupport': True, 'dynamicRegistration': True}, 'documentHighlight': {'dynamicRegistration': True}}, 'window': {'showMessage': {'messageActionItem': {'additionalPropertiesSupport': True}}, 'workDoneProgress': True}}, 'initializationOptions': {}, 'rootUri': 'file:///D:/Programming/odin-project', 'workspaceFolders': [{'uri': 'file:///D:/Programming/odin-project', 'name': 'odin-project'}]}
lsp-typescript: INFO: Could not find files for the given pattern(s).
:: <<< lsp-typescript 1: {'capabilities': {'referencesProvider': True, 'workspaceSymbolProvider': True, 'completionProvider': {'resolveProvider': True, 'triggerCharacters': ['.', '"', "'", '/', '@', '<']}, 'definitionProvider': True, 'callsProvider': True, 'typeDefinitionProvider': True, 'hoverProvider': True, 'renameProvider': True, 'executeCommandProvider': {'commands': ['_typescript.applyWorkspaceEdit', '_typescript.applyCodeAction', '_typescript.applyRefactoring', '_typescript.organizeImports', '_typescript.applyRenameFile']}, 'documentFormattingProvider': True, 'documentHighlightProvider': True, 'foldingRangeProvider': True, 'codeActionProvider': True, 'textDocumentSync': 2, 'signatureHelpProvider': {'triggerCharacters': ['(', ',', '<']}, 'documentRangeFormattingProvider': True, 'implementationProvider': True, 'documentSymbolProvider': True}}
```
