### ISSUE TITLE
Bad experience when jumping to next errors while removing them

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1334] opened 2020-09-18 18:35 UTC
**Describe the bug**
The "jump to next issue" command (F4 key) does not reliably trigger if the error was just removed. Only when new diagnostics are received it works again.

**To Reproduce**
1. With LSP-json enabled, save this JSON content in a random file:

<details>
<summary>random.json</summary>

```
{
	"contributions": {
		"settings": [
			{
				"file_patterns": [
					"/LSP-lemminx.sublime-settings"
				],
				"schema": {
					"$id": "sublime://settings/LSP-lemminx",
					"definitions": {
						"PluginConfig": {
							"properties": {
								"settings": {
									"type": "object",
									"properties": {
										"xml.trace.server": {
											"type": "string",
											"enum": [
												"off",
												"messages",
												"verbose"
											],
											"default": "off",
											"description": "Traces the communication between VS Code and the XML language server.",
											"scope": "window"
										},
										"xml.catalogs": {
											"type": "array",
											"default": [],
											"items": {
												"type": "string"
											},
											"description": "Array of XML Catalogs.",
											"scope": "window"
										},
										"xml.logs.client": {
											"type": "boolean",
											"default": true,
											"description": "Should the server log to client output."
										},
										"xml.format.emptyElements": {
											"type": "string",
											"enum": [
												"ignore",
												"collapse",
												"expand"
											],
											"default": "ignore",
											"description": "Expand/collapse empty elements.",
											"scope": "window"
										},
										"xml.format.preserveAttributeLineBreaks": {
											"type": "boolean",
											"default": false,
											"markdownDescription": "Preserve line breaks that appear before and after attributes. This setting is overridden if `#xml.format.splitAttributes#` is set to `true`.",
											"scope": "window"
										},
										"xml.format.splitAttributes": {
											"type": "boolean",
											"default": false,
											"description": "Split multiple attributes each onto a new line.",
											"scope": "window"
										},
										"xml.format.joinCDATALines": {
											"type": "boolean",
											"default": false,
											"description": "Join lines in a CDATA tag's content.",
											"scope": "window"
										},
										"xml.format.joinCommentLines": {
											"type": "boolean",
											"default": false,
											"description": "Join comment content on format.",
											"scope": "window"
										},
										"xml.format.spaceBeforeEmptyCloseTag": {
											"type": "boolean",
											"default": true,
											"description": "Insert space before end of self closing tag. \nExample:\n  <tag/> -> <tag />",
											"scope": "window"
										},
										"xml.format.joinContentLines": {
											"type": "boolean",
											"default": false,
											"description": "Normalize the whitespace of content inside an element. Newlines and excess whitespace are removed.",
											"scope": "window"
										},
										"xml.format.preserveEmptyContent": {
											"type": "boolean",
											"default": false,
											"description": "Preserve empty content/whitespace in a tag.",
											"scope": "window"
										},
										"xml.format.preservedNewlines": {
											"type": "integer",
											"enum": [
												0,
												1,
												2,
												3
											],
											"default": 2,
											"description": "Preserve new lines that separate tags. The value represents the maximum number of new lines per section. A value of 0 removes all new lines.",
											"scope": "window"
										},
										"xml.format.enabled": {
											"type": "boolean",
											"default": true,
											"description": "Enable/disable ability to format document.",
											"scope": "window"
										},
										"xml.format.enforceQuoteStyle": {
											"type": "string",
											"enum": [
												"preferred",
												"ignore"
											],
											"markdownEnumDescriptions": [
												"Use preferred quote style set by `xml.preferences.quoteStyle` when formatting.",
												"Ignore quote style formatting."
											],
											"default": "ignore",
											"markdownDescription": "Enforce `preferred` quote style (set by `#xml.preferences.quoteStyle#`) or `ignore` quote style when formatting. Default is `ignore`",
											"scope": "window"
										},
										"xml.preferences.quoteStyle": {
											"type": "string",
											"enum": [
												"single",
												"double"
											],
											"default": "double",
											"markdownDescription": "Preferred quote style to use for completion: `single` quotes, `double` quotes.",
											"scope": "window"
										},
										"xml.fileAssociations": {
											"type": "array",
											"default": [],
											"items": {
												"type": "object",
												"properties": {
													"systemId": {
														"type": "string",
														"description": "The path or URL to the XML schema (XSD or DTD)."
													},
													"pattern": {
														"type": "string",
														"description": "File glob pattern. Example: **/*.Format.ps1xml\n\nMore information on the glob syntax: https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob",
														"markdownDescription": "File glob pattern. Example: `**/*.Format.ps1xml`\n\nMore information on the glob syntax: https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob"
													}
												},
												"required": [
													"systemId",
													"pattern"
												]
											},
											"description": "Allows XML schemas to be associated to file name patterns.\n\nExample:\n[{\n  \"systemId\": \"path/to/file.xsd\",\n  \"pattern\": \"file1.xml\"\n},\n{\n  \"systemId\": \"http://www.w3.org/2001/XMLSchema.xsd\",\n  \"pattern\": \"**/*.xsd\"\n}]",
											"markdownDescription": "Allows XML schemas to be associated to file name patterns.\n\nExample:\n```json\n[{\n  \"systemId\": \"path/to/file.xsd\",\n  \"pattern\": \"file1.xml\"\n},\n{\n  \"systemId\": \"http://www.w3.org/2001/XMLSchema.xsd\",\n  \"pattern\": \"**/*.xsd\"\n}]\n```",
											"scope": "window"
										},
										"xml.completion.autoCloseTags": {
											"type": "boolean",
											"default": true,
											"description": "Enable/disable autoclosing of XML tags. \n\nIMPORTANT: Turn off editor.autoClosingTags for this to work.",
											"scope": "window"
										},
										"xml.codeLens.enabled": {
											"type": "boolean",
											"default": false,
											"description": "Enable/disable XML CodeLens."
										},
										"xml.preferences.showSchemaDocumentationType": {
											"type": "string",
											"default": "all",
											"enum": [
												"documentation",
												"appinfo",
												"all",
												"none"
											],
											"markdownEnumDescriptions": [
												"Documentation comes from the `xs:documentation` element.",
												"Documentation comes from the `xs:appinfo` element.",
												"Documentation comes from the `xs:documentation` and `xs:appinfo` elements.",
												"Displays no documentation."
											],
											"description": "Specifies the source of the XML schema documentation displayed on hover and completion.",
											"scope": "window"
										},
										"xml.java.home": {
											"type": [
												"string",
												"null"
											],
											"default": null,
											"description": "Specifies the folder path to the JDK (8 or more recent) used to launch the XML Language Server.\nOn Windows, backslashes must be escaped, i.e.\n\"xml.java.home\": \"C:\\\\Program Files\\\\Java\\\\jdk1.8.0_161\"",
											"scope": "window"
										},
										"xml.server.vmargs": {
											"type": [
												"string",
												"null"
											],
											"default": "-Xmx64M -XX:+UseG1GC -XX:+UseStringDeduplication",
											"description": "Specifies extra VM arguments used to launch the XML Language Server. Eg. use `-Xmx1G  -XX:+UseG1GC -XX:+UseStringDeduplication` to bypass class verification, increase the heap size to 1GB and enable String deduplication with the G1 Garbage collector.",
											"scope": "window"
										},
										"xml.server.workDir": {
											"type": "string",
											"default": "~/.lemminx",
											"description": "Set a custom folder path for cached XML Schemas. An absolute path is expected, although the ~ prefix (for the user home directory) is supported.",
											"scope": "window"
										},
										"xml.validation.noGrammar": {
											"type": "string",
											"enum": [
												"ignore",
												"hint",
												"info",
												"warning",
												"error"
											],
											"default": "hint",
											"description": "The message severity when a document has no associated grammar.",
											"scope": "window"
										},
										"xml.validation.enabled": {
											"type": "boolean",
											"default": true,
											"description": "Enable/disable all validation.",
											"scope": "window"
										},
										"xml.validation.schema": {
											"type": "boolean",
											"default": true,
											"description": "Enable/disable schema based validation. Ignored if \"xml.validation.enabled\": false.",
											"scope": "window"
										},
										"xml.validation.disallowDocTypeDecl": {
											"type": "boolean",
											"default": false,
											"description": "Enable/disable if a fatal error is thrown if the incoming document contains a DOCTYPE declaration.",
											"scope": "window"
										},
										"xml.validation.resolveExternalEntities": {
											"type": "boolean",
											"default": false,
											"description": "Enable/disable resolve of external entities.",
											"scope": "window"
										},
										"xml.symbols.enabled": {
											"type": "boolean",
											"default": true,
											"description": "Enable/disable document symbols (Outline). No symbols are given if `\"xml.symbol.enabled\": false`.",
											"scope": "window"
										},
										"xml.symbols.excluded": {
											"type": "array",
											"default": [],
											"items": {
												"type": "string"
											},
											"description": "Disable document symbols (Outline) for the given file name patterns. Updating file name patterns does not automatically reload the Outline view for the relevant file(s). Each file must either be reopened or changed, in order to trigger an Outline view reload.\n\nExample:\n[\n \"**/*LargeFile.xml\"\n]",
											"scope": "window"
										},
										"xml.symbols.maxItemsComputed": {
											"type": "integer",
											"default": 5000,
											"description": "The maximum number of outline symbols and folding regions computed (limited for performance reasons)."
										}
									}
								}
							}
						}
					},
					"allOf": [
						{
							"$ref": "sublime://settings/LSP-plugin-base"
						},
					],
				}
			},
			{
				"file_patterns": [
					"/LSP.sublime-settings"
				],
				"schema": {
					"properties": {
						"clients": {
						}
					}
				}
			},
			{
				"file_patterns": [
					"/*.sublime-project"
				],
				"schema": {
					"properties": {
						"settings": {
							"properties": {
								"LSP": {
									"properties": {
									}
								}
							}
						}
					}
				}
			},
		]
	}
}
```

</details>

2. Jump to the next error (trailing comma), remove the comma, and jump to the next error immediately

**Expected behavior**
Always jumping to the next error.

**Actual behavior**
Jumping to the next error doesn't work immediately after removing the error. Only after diagnostics are updated the jump works.

**Environment (please complete the following information):**
- Sublime Text version: 4086
- LSP version: 1.0.16

**Comment by rchl** [comment] 2020-09-18 18:36
Hmm, also not sure now about the behavior of "next_result" command. It doesn't seem to always work for navigating the errors.

**Comment by rwols** [comment] 2020-10-24 18:59
I am surprised "next_result" actually works. Why does it work at all? All we do is call view.add_regions, right? Do these regions automatically count towards a view's "problems"?

**Comment by rchl** [comment] 2020-10-24 21:08
I suppose it might have something to do with the diagnostics panel and the scopes used there?
I don't honestly know but it doesn't seem to work very reliably according to my expectations at least.

**Comment by rwols** [comment] 2020-12-30 16:24
I'll consider this an ST issue.

The problem is that ST doesn't have a notion of diagnostics at all, or a notion of a problems panel like VSCode.

Therefore ST can also never have the notion/concept of "diagnostics version" (or change_count). If ST could account for stale diagnostics having an older version than the change count, it could decide to not jump to the next problem/diagnostic in the panel.

**Comment by rwols** [comment] 2020-12-30 16:26
I mean exactly the same problem occurs when you have a build system with a file or line regex, and the annotations appear in the view, and you edit the view, and then you can still go to the "next" problem while that's completely out-of-sync now.

**Comment by rchl** [comment] 2021-01-02 20:31
But build system results are created at the time of running the build so at least I would expect them to get outdated. LSP is supposed to give live feedback so it feels like a bug to me.

**Comment by rchl** [comment] 2021-01-02 20:37
As far as fixing or improving this issue, I guess the best we could do is making things clearer to the user somehow. The diagnostic update is obviously delayed a bit after editing the document so we can't guarantee that "jump to next" will work right away. Although the user might think it should work because the (error) region of the diagnostic is still kept visible during that time the diagnostics are updating. So that might be the most confusing thing - the error is still visible in the view but you jumping to it doesn't work.

**Comment by rwols** [comment] 2021-01-03 11:55
So we should remove diagnostics once the buffer is modified?

**Comment by rchl** [comment] 2021-01-03 12:53
I think we could try that but probably would have to have some heuristic as otherwise, it could be too distracting.

**Comment by predragnikolic** [comment] 2022-09-19 22:01
Fixed with https://github.com/sublimelsp/LSP/pull/2054

There are new keybindings for navigating to next/prev diagnostics.
See https://github.com/sublimelsp/LSP/pull/2054/files#diff-a63cf66b08284ab9b0b463ff90e213ce79cef12b9f4682e9d48351acb2aa84a5

**Closed by predragnikolic** 2022-09-19 22:01 UTC
Labels: sublime issue
