### ISSUE TITLE
No diagnostics are shown if folders are open

### ISSUE THREAD

**Issue by Sainan** [sublimelsp/LSP#2120] opened 2022-11-19 23:34 UTC
**Describe the bug**
The LSP plugin ignores any diagnostics published by the language server if a) at least one folder is opened in sublime text, and b) the affected source file(s) are not within that/those folder(s).

**To Reproduce**
1. Drag a folder into Sublime Text
2. Open a source file that is not within that folder's tree

**Expected behavior**
The diagnostics should still be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/63328889/202875686-1c09c857-4561-4865-b326-18301a9ca36e.png)
(Language Server published 2 diagnostics, none are shown in Sublime Text.)

**Environment:**
- OS: Windows 10
- Sublime Text version: 4143
- LSP version: 1.20.0
- Language servers used: [pluto-language-server](https://github.com/PlutoLang/pluto-language-server) (TCP)

**Comment by rwols** [comment] 2022-11-20 08:46
Duplicate of https://github.com/sublimelsp/LSP/issues/1835?

**Comment by rchl** [comment] 2022-11-20 13:47
Does this server have any functionality that depends on having a project folder or it works the same regardless if opening single file or a project?

**Comment by Sainan** [comment] 2022-11-20 17:30
> Does this server have any functionality that depends on having a project folder or it works the same regardless if opening single file or a project?

No, as you can see in the provided screenshot, the server published the diagnostics, the LSP plugin just isn't showing them.

**Comment by rchl** [comment] 2022-11-20 17:53
I know. I've asked in context of https://github.com/sublimelsp/LSP/issues/1835 where there is discussion on how to name the new option for that.

**Comment by rchl** [comment] 2022-11-20 17:56
But yes, it's a duplicate of https://github.com/sublimelsp/LSP/issues/1835?

**Closed by rchl** 2022-11-20 17:56 UTC
