### ISSUE TITLE
Still shows diagnostics on closed files

### ISSUE THREAD

**Issue by reagle** [sublimelsp/LSP#1925] opened 2021-12-30 15:49 UTC
Perhaps this is related to #1921. Sometimes I open a python file that has ton of linter problems but which I can't change. However, when I close the file, its diagnostics continue to pollute the diagnostic panel until I exit ST. This unfortunately obscures any problems I might have in the python files that I keep linted. Is this a bug? Configurable? Similarly, it'd be nice if the diagnostic panel view moved to the start of the diagnostics for the current visible pane/tab.

1. Open a file with many diagnostics.
2. Close the file and the diagnostics persist.

- macOS 12.1 21C52 arm64 using ST 4126 with LSP 1.15.0 and LSP-pylsp 2.3.1.
- 
<img width="775" alt="Screen Shot 2021-12-30 at 10 46 19" src="https://user-images.githubusercontent.com/596814/147767120-bd57c0ab-f689-49d5-b692-7d8e0943eab5.png">

**Comment by rwols** [comment] 2021-12-30 16:16
The server is responsible for clearing the diagnostics.

https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics

> Diagnostics are “owned” by the server so it is the server’s responsibility to clear them if necessary.

However I'm wondering whether clearing the diagnostic contributions from the panel when the session exits is handled correctly. To determine that, could you enable debug logging in LSP and share the contents of LSP's Log Panel? See: https://lsp.sublimetext.io/troubleshooting/#self-help-instructions

**Comment by rwols** [comment] 2021-12-30 16:37
I think you can test the hypothesis by opening two python files, and then closing the one with the many diagnostics. Do the diagnostics then disappear?

**Comment by reagle** [comment] 2021-12-30 17:08
```
:: --> LSP-pylsp initialize(1): {'initializationOptions': {}, 'rootPath': None, 'rootUri': None, 'capabilities': {'general': {'markdown': {'version': '3.2.2', 'parser': 'Python-Markdown'}, 'regularExpressions': {'engine': 'ECMAScript'}}, 'textDocument': {'documentSymbol': {'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'hierarchicalDocumentSymbolSupport': True, 'tagSupport': {'valueSet': [1]}}, 'codeLens': {'dynamicRegistration': True}, 'definition': {'dynamicRegistration': True, 'linkSupport': True}, 'selectionRange': {'dynamicRegistration': True}, 'synchronization': {'dynamicRegistration': True, 'didSave': True, 'willSaveWaitUntil': True, 'willSave': True}, 'completion': {'dynamicRegistration': True, 'completionItem': {'insertTextModeSupport': {'valueSet': [2]}, 'deprecatedSupport': True, 'documentationFormat': ['markdown', 'plaintext'], 'resolveSupport': {'properties': ['detail', 'documentation', 'additionalTextEdits']}, 'labelDetailsSupport': True, 'tagSupport': {'valueSet': [1]}, 'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'insertTextMode': 2}, 'documentHighlight': {'dynamicRegistration': True}, 'references': {'dynamicRegistration': True}, 'formatting': {'dynamicRegistration': True}, 'publishDiagnostics': {'versionSupport': True, 'dataSupport': True, 'tagSupport': {'valueSet': [2, 1]}, 'relatedInformation': True, 'codeDescriptionSupport': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'hover': {'dynamicRegistration': True, 'contentFormat': ['markdown', 'plaintext']}, 'signatureHelp': {'dynamicRegistration': True, 'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'codeAction': {'dynamicRegistration': True, 'resolveSupport': {'properties': ['edit']}, 'dataSupport': True, 'codeActionLiteralSupport': {'codeActionKind': {'valueSet': ['quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source.organizeImports']}}}, 'rename': {'dynamicRegistration': True, 'prepareSupport': True}, 'typeDefinition': {'dynamicRegistration': True, 'linkSupport': True}, 'declaration': {'dynamicRegistration': True, 'linkSupport': True}, 'colorProvider': {'dynamicRegistration': True}, 'implementation': {'dynamicRegistration': True, 'linkSupport': True}, 'semanticTokens': {'dynamicRegistration': True, 'overlappingTokenSupport': False, 'multilineTokenSupport': True, 'tokenTypes': ['variable', 'enumMember', 'modifier', 'operator', 'typeParameter', 'method', 'comment', 'parameter', 'number', 'function', 'class', 'type', 'regexp', 'namespace', 'macro', 'interface', 'event', 'string', 'property', 'struct', 'enum', 'keyword'], 'requests': {'range': True, 'full': {'delta': True}}, 'formats': ['relative'], 'tokenModifiers': ['definition', 'abstract', 'deprecated', 'readonly', 'modification', 'static', 'declaration', 'documentation', 'async', 'defaultLibrary']}}, 'workspace': {'didChangeConfiguration': {'dynamicRegistration': True}, 'configuration': True, 'workspaceFolders': True, 'semanticTokens': {'refreshSupport': True}, 'symbol': {'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'tagSupport': {'valueSet': [1]}}, 'applyEdit': True, 'executeCommand': {}, 'workspaceEdit': {'failureHandling': 'abort', 'documentChanges': True}, 'codeLens': {'refreshSupport': True}}, 'window': {'showMessage': {'messageActionItem': {'additionalPropertiesSupport': True}}, 'showDocument': {'support': True}, 'workDoneProgress': True}}, 'processId': 8263, 'workspaceFolders': None, 'clientInfo': {'name': 'Sublime Text LSP', 'version': '1.15.0'}}
:: <<< LSP-pylsp 1: {'serverInfo': {'name': 'pylsp', 'version': '1.3.3'}, 'capabilities': {'renameProvider': True, 'codeLensProvider': {'resolveProvider': False}, 'experimental': {}, 'foldingRangeProvider': True, 'codeActionProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(', ',', '=']}, 'executeCommandProvider': {'commands': []}, 'referencesProvider': True, 'definitionProvider': True, 'documentHighlightProvider': True, 'workspace': {'workspaceFolders': {'changeNotifications': True, 'supported': True}}, 'documentFormattingProvider': True, 'documentSymbolProvider': True, 'documentRangeFormattingProvider': True, 'textDocumentSync': {'didClose': {}, 'save': {'includeText': True}, 'didOpen': {}, 'change': {'syncKind': 2}}, 'completionProvider': {'triggerCharacters': ['.'], 'resolveProvider': True}, 'hoverProvider': True}}
::  -> LSP-pylsp initialized: {}
::  -> LSP-pylsp workspace/didChangeConfiguration: {'settings': {'pylsp': {'plugins': {'jedi_signature_help': {'enabled': True}, 'flake8': {'enabled': True, 'config': None, 'perFileIgnores': ['emit_biblatex.py:E203,E241,E701,E117,W503', 'emit_yaml_csl.py:E203,E241,E701,E117,W503', 'biblio_fields.py:E241'], 'select': None, 'ignore': None, 'exclude': None, 'executable': 'flake8', 'maxLineLength': None, 'filename': None, 'hangClosing': None}, 'autopep8': {'enabled': True}, 'mccabe': {'enabled': False, 'threshold': 15}, 'mypy_ls': {'enabled': False}, 'rope_completion': {'eager': False, 'enabled': True}, 'pydocstyle': {'convention': None, 'addSelect': None, 'addIgnore': None, 'match': '(?!test_).*\\.py', 'select': None, 'ignore': None, 'matchDir': '[^\\.].*', 'enabled': False}, 'pylsp_mypy': {'dmypy': False, 'enabled': False, 'strict': False, 'live_mode': True}, 'jedi_definition': {'follow_imports': True, 'enabled': True, 'follow_builtin_imports': True}, 'pyls_isort': {'enabled': True}, 'pylsp_black': {'enabled': False}, 'yapf': {'enabled': False}, 'pyflakes': {'enabled': False}, 'jedi': {'extra_paths': ['/Applications/Sublime Text.app/Contents/MacOS/Lib/python33', '/Users/reagle/Library/Application Support/Sublime Text 3/Packages'], 'environment': None, 'env_vars': None}, 'preload': {'enabled': True, 'modules': None}, 'jedi_symbols': {'all_scopes': True, 'enabled': True, 'include_import_symbols': True}, 'jedi_references': {'enabled': True}, 'jedi_completion': {'cache_for': ['pandas', 'numpy', 'tensorflow', 'matplotlib'], 'resolve_at_most': 25, 'eager': False, 'enabled': True, 'include_params': True, 'include_class_objects': True, 'fuzzy': True}, 'pycodestyle': {'enabled': False, 'hangClosing': None, 'aggressive': None, 'ignore': None, 'exclude': None, 'select': None, 'maxLineLength': None, 'filename': None}, 'pylint': {'enabled': False, 'executable': '', 'args': None}, 'jedi_hover': {'enabled': True}, 'mypy-ls': {'strict': False, 'live_mode': False}}, 'configurationSources': ['flake8'], 'rope': {'ropeFolder': None, 'extensionModules': None}}}}
::  -> LSP-pylsp textDocument/didOpen: {'textDocument': {'text': '#!/usr/bin/env python3\n# DESCRIPTION\n# (c) Copyright 2022 by Joseph Reagle\n# Licensed under the GPLv3, see <http://www.gnu.org/licenses/gpl-3.0.html>\n#\n\nfrom glob import glob\nfrom os import chdir, environ, mkdir, path, rename, remove, walk\nfrom os.path import exists, isfile\nfrom pathlib import Path  # https://docs.python.org/3/library/pathlib.html\nfrom sh import git, find, ls, wc  # http://amoffat.github.io/sh/index.html\nfrom sh import pandoc, wc, wget\nfrom shutil import copy\nimport argparse  # http://docs.python.org/dev/library/argparse.html\nimport os\nimport re\nimport sh\nimport sys\n\nHOME = str(Path("~").expanduser())\n\n\ndef main(argv):\n    """Process arguments"""\n    arg_parser = argparse.ArgumentParser(description="TBD")\n\n    # positional arguments\n    arg_parser.add_argument("files", nargs="?", metavar="FILE")\n    # optional arguments\n    arg_parser.add_argument(\n        "-b",\n        "--boolean",\n        action="store_true",\n        default=False,\n        help="boolean value",\n    )\n    arg_parser.add_argument("--version", action="version", version="TBD")\n    args = arg_parser.parse_args(argv)\n\n    return args\n\n\nif __name__ == "__main__":\n    args = main(sys.argv[1:])\n\n# Passing Arguments\nls("-l", "/tmp", color="never")\n\n\n# Exit Codes\ntry:\n    ls("/doesnt/exist")\nexcept sh.ErrorReturnCode_2:\n    print("directory doesn\'t exist")\n\n# Redirection\nls(_out="/tmp/dir_contents")\n\nwith open("/tmp/dir_contents", "w") as h:\n    ls(_out=h)\n\n\n# Baking/alias\nmy_ls = ls.bake("-l")\n# equivalent\nmy_ls("/tmp")\nls("-l", "/tmp")\n\n# Piping\nwc(ls("-1"), "-l")\n\n# Subcommands\ngit("show", "HEAD")\n# equivalent\ngit.show("HEAD")\n\n# Background Processes\np = find("-name", "sh.py", _bg=True)\n# ... do other things ...\np.wait()\n', 'uri': 'file:///Users/reagle/bin/_quick-template.py', 'version': 0, 'languageId': 'python'}}
:: --> LSP-pylsp textDocument/codeLens(2): {'textDocument': {'uri': 'file:///Users/reagle/bin/_quick-template.py'}}
:: <<< LSP-pylsp 2: []
:: <-  LSP-pylsp textDocument/publishDiagnostics: {'diagnostics': [{'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 22, 'line': 6}, 'start': {'character': 0, 'line': 6}}, 'code': 'F401', 'message': "F401 'glob.glob' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 65, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'code': 'F401', 'message': "F401 'os.chdir' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 65, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'code': 'F401', 'message': "F401 'os.environ' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 65, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'code': 'F401', 'message': "F401 'os.mkdir' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 65, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'code': 'F401', 'message': "F401 'os.path' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 65, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'code': 'F401', 'message': "F401 'os.rename' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 65, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'code': 'F401', 'message': "F401 'os.remove' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 65, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'code': 'F401', 'message': "F401 'os.walk' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 35, 'line': 8}, 'start': {'character': 0, 'line': 8}}, 'code': 'F401', 'message': "F401 'os.path.exists' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 35, 'line': 8}, 'start': {'character': 0, 'line': 8}}, 'code': 'F401', 'message': "F401 'os.path.isfile' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 32, 'line': 11}, 'start': {'character': 0, 'line': 11}}, 'code': 'F811', 'message': "F811 redefinition of unused 'wc' from line 11"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 32, 'line': 11}, 'start': {'character': 0, 'line': 11}}, 'code': 'F401', 'message': "F401 'sh.pandoc' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 32, 'line': 11}, 'start': {'character': 0, 'line': 11}}, 'code': 'F401', 'message': "F401 'sh.wget' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 24, 'line': 12}, 'start': {'character': 0, 'line': 12}}, 'code': 'F401', 'message': "F401 'shutil.copy' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 10, 'line': 14}, 'start': {'character': 0, 'line': 14}}, 'code': 'F401', 'message': "F401 'os' imported but unused"}, {'source': 'flake8', 'severity': 2, 'range': {'end': {'character': 10, 'line': 15}, 'start': {'character': 0, 'line': 15}}, 'code': 'F401', 'message': "F401 're' imported but unused"}], 'uri': 'file:///Users/reagle/bin/_quick-template.py'}
:: --> LSP-pylsp textDocument/codeAction(3): {'textDocument': {'uri': 'file:///Users/reagle/bin/_quick-template.py'}, 'range': {'end': {'character': 0, 'line': 0}, 'start': {'character': 0, 'line': 0}}, 'context': {'diagnostics': []}}
:: <<< LSP-pylsp 3: []
:: --> LSP-pylsp textDocument/documentHighlight(4): {'position': {'character': 0, 'line': 38}, 'textDocument': {'uri': 'file:///Users/reagle/bin/_quick-template.py'}}
:: --> LSP-pylsp textDocument/codeAction(5): {'textDocument': {'uri': 'file:///Users/reagle/bin/_quick-template.py'}, 'range': {'end': {'character': 0, 'line': 38}, 'start': {'character': 0, 'line': 38}}, 'context': {'diagnostics': []}}
:: <<< LSP-pylsp 4: None
:: <<< LSP-pylsp 5: []
::  -> LSP-pylsp textDocument/didClose: {'textDocument': {'uri': 'file:///Users/reagle/bin/_quick-template.py'}}
:: --> LSP-pylsp shutdown(6): None
:: <<< LSP-pylsp 6: None
::  -> LSP-pylsp exit: None
```

**Comment by reagle** [comment] 2021-12-30 17:09
I opened the file, saw the many diagnostics, and then close the file yet the diagnostics remained.

> I think you can test the hypothesis by opening two python files, and then closing the one with the many diagnostics. Do the diagnostics then disappear?

No, that is my point. In the screen shot, no file is open, yet you can still see them.

**Comment by rwols** [comment] 2021-12-30 17:17
From the logs I can see that you had one file open, then closed that one file.

Now try opening two files (have two tabs open), then close exactly one file and wait a few seconds. Do the diagnostics then disappear?

The connection to the language server subprocess is automatically ended when for at least three seconds no more tabs are open. I am wondering whether we handle the case where the connection is ended while the server hasn't yet published empty diagnostics yet.

**Comment by reagle** [comment] 2021-12-30 17:23
I've attached a two file log. The diagnostics for an opened file never disappear.  

[lsp-log.txt](https://github.com/sublimelsp/LSP/files/7793927/lsp-log.txt)

**Comment by rwols** [comment] 2021-12-30 17:45
Then at least this is a pyls issue. What do you think @htmue?

**Comment by rwols** [comment] 2021-12-30 20:03
The only call to textDocument/publishDiagnostics in pylsp seems to be here: https://github.com/python-lsp/python-lsp-server/blob/03ab6efdec1d53b9d2359caa376ef12269b81cb5/pylsp/python_lsp.py#L292-L300

Our textDocument/didClose notification is handled here: https://github.com/python-lsp/python-lsp-server/blob/03ab6efdec1d53b9d2359caa376ef12269b81cb5/pylsp/python_lsp.py#L320-L322

that method doesn't clear the diagnostics, so I'm fairly sure this is a pylsp issue.

**Closed by rwols** 2021-12-30 20:03 UTC
Labels: language server issue

**Comment by reagle** [comment] 2021-12-30 22:44
@rwols, I think @krassowski is saying this issue should be resolved here.

**Comment by krassowski** [comment] 2021-12-31 00:27
No, this is not what I was saying. There are two issues, one with the server and the other non related to server, which is:

> Similarly, it'd be nice if the diagnostic panel view moved to the start of the diagnostics for the current visible pane/tab.

**Comment by htmue** [comment] 2022-01-04 11:31
> Then at least this is a pyls issue. What do you think @htmue?

Clearing diagnostics is the responsibility of the server, as discussed in https://github.com/python-lsp/python-lsp-server/issues/143.

> Similarly, it'd be nice if the diagnostic panel view moved to the start of the diagnostics for the current visible pane/tab.

This could be done, but interfering with ST's result handling when switching buffers would lead to other issues, I think.

@reagle: There is a way to access diagnostics for the current file only: Goto -> LSP: Goto Diagnostics... in the main menu. Maybe this helps with your issue?

**Comment by reagle** [comment] 2022-01-04 14:14
@htmue, thanks for the tip. Unfortunately, even though ST4126 is otherwise solid for me (and ST has been for a long time) that particular command causes a crash without any diagnostics.

**Comment by rchl** [comment] 2022-01-04 14:49
The whole ST crashes?

The command is not supposed to even be enabled when there are no diagnostics:

![Screenshot 2022-01-04 at 15 49 36](https://user-images.githubusercontent.com/153197/148076907-50ee836b-1879-453d-9f15-09fb3ad7da6c.png)

How are you triggering that command exactly?

**Comment by reagle** [comment] 2022-01-04 16:05
Yes, ST crashes. Here's the process:

1. Leave my project as only files within the project seem to be linted and everything behaves there. So I return to default/clean project.
2. Re-open a project python file.
3. Open a poorly-styled python file.
4. Use shortcut or palette to `Toggle diagnostic panel,` and it shows lints for both.
5. Command palette, select `LSP: Goto Diagnostic...` and ST quits.

**Comment by rchl** [comment] 2022-01-05 22:09
Feel free to create a separate issue for it.
Crashes are ST issues but we should figure out a minimal repro before filing an ST issue so you can create one here instead.

Note that your reproduction steps need to be more detailed since I can't figure out how to reproduce from the steps you've posted.
