### ISSUE TITLE
Error handling None in Console

### ISSUE THREAD

**Issue by LDAP** [sublimelsp/LSP#1886] opened 2021-11-01 13:51 UTC
**Describe the bug**
Console gets filed with error messages

**To Reproduce**
1. Install LSP, LSP-jdtls
2. Open Java file

**Expected behavior**
Nothing

**Screenshots**
none

**Environment (please complete the following information):**
- OS: Manjaro Linux
- Sublime Text version: 4121
- LSP version: 1.13

**Additional context**
I installed LSP-file-watcher-chokidar

**Log**
[log.txt](https://github.com/sublimelsp/LSP/files/7453704/log.txt)

**Comment by rchl** [comment] 2021-11-01 14:15
For the record:

```

Error handling None
Traceback (most recent call last):
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 1612, in on_payload
    handler(result)
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 1546, in <lambda>
    self.send_request_async(request, resolver, lambda x: resolver(Error.from_lsp(x)))
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 153, in <lambda>
    executor_func(lambda value=None: self._do_resolve(value))
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 214, in _do_resolve
    callback(new_value)
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 178, in callback_wrapper
    result = onfullfilled(resolve_value)
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/code_lens.py", line 60, in resolve
    self.region = range_to_region(Range.from_lsp(code_lens['range']), view)
TypeError: 'Error' object is not subscriptable

Traceback (most recent call last):
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/code_actions.py", line 65, in <lambda>
  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 538, in _on_code_actions
KeyError: 'foreground'
```

**Comment by jwortmann** [comment] 2021-11-02 19:06
Are those 2 independent errors?

> ```
> Traceback (most recent call last):
>  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/code_actions.py", line 65, in <lambda>
>  File "/.../sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 538, in _on_code_actions
> KeyError: 'foreground'
> ```

This error makes no sense to me. `View.style_for_scope()` should always return a dict with a "foreground" key, both according to the API documentation, as well as when I test it in the console. If there is no color scheme rule for the specified scope, then it will be set to the global foreground color. And even if there exists a rule for the scope, but the rule doesn't assign a foreground color, then the returned dict still has the "foreground" key with the default foreground:
with this color scheme rule
```json
        {
            "scope": "this-has-only-background",
            "background": "red"
        },
```
I get
```
>>> view.style_for_scope("this-has-only-background")["foreground"]
'#dddddd'
```
which is the default foreground in my color scheme.

Anyways, a fix for this obscure error could be something like
```python
annotation_color = self.view.style_for_scope("region.bluish markup.accent.codeaction.lsp").get("foreground", "#0000ff")
```
instead of
```python
annotation_color = self.view.style_for_scope("region.bluish markup.accent.codeaction.lsp")["foreground"]
```

**Comment by LDAP** [comment] 2021-11-02 19:52
Could be possible that these are independent. Though, I never saw the second Traceback without at least one instance of the first one.

**Comment by rchl** [comment] 2021-11-02 20:05
If my guess is right as for what the main issue is, the #1888 should fix it.

I'll leave the color scheme related issue out for now. We can see if it still triggers with the main fix.

**Comment by rchl** [comment] 2021-11-02 20:07
Actually I'm not sure about the fix since we should not be even attempting to resolve if the code action is already resolved. Can you enable `log_server` (https://lsp.sublimetext.io/troubleshooting/) and post the log around the time when it fails?

**Comment by LDAP** [comment] 2021-11-02 22:05
Heres an excerpt of the log that shows the relevant part (I had to remove some work-related information):
[log.txt](https://github.com/sublimelsp/LSP/files/7464232/log.txt)

**Comment by rchl** [comment] 2021-11-03 08:38
OK, so it looks that the code lens resolve requests are failing because the file was closed which is expected.

With that information, I should try to reproduce and see what happens with my fix. I would still expect some issues since we call various APIs after the file is closed. That should also explain the issue with `view.style_for_scope("this-has-only-background")` return `None` since the file was closed already.

**Comment by jwortmann** [comment] 2021-11-03 15:25
`View.style_for_scope()` seems to return an empty dict if the view was closed. For some reason I had assumed that `self.view` of the `ViewEventListener` would be `None` if the view was closed, but apparently that is not the case and it is still a reference to the old `View` object, and its method calls are still allowed. This means that a check like `if view:` wouldn't work here, but instead we could add a check to return early from the function, because `add_regions()` wouldn't do anything then.
```python
annotation_color = self.view.style_for_scope("region.bluish markup.accent.codeaction.lsp").get("foreground")
if annotation_color is None:
    return
```

I guess the ST API is missing a method like `View.is_open()`, which would make things easier for long running operations.

**Comment by rchl** [comment] 2021-11-03 20:41
I've added a check for whether `ViewEventListener` is alive. It should fix both errors.

**Closed** 2021-11-06 18:59 UTC
Labels: bug
