### ISSUE TITLE
Text selection in popups

### ISSUE THREAD

**Issue by silverwind** [sublimelsp/LSP#2486] opened 2024-05-29 08:16 UTC
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to select code inside the popups provided by LSP. This is also possible in VSCode, for example. Does ST's API allow this or would it be a upstream issue?

**Describe the solution you'd like**
Allow text selection and subsequent copying of the code.

**Describe alternatives you've considered**
No alternatives besides typing out manually.

**Additional context**
<img width="541" alt="image" src="https://github.com/sublimelsp/LSP/assets/115237/2d020192-4a30-4cea-97f4-e9cce063ffc8">

**Comment by predragnikolic** [comment] 2024-05-29 08:37
Hello, 

Closing this as a duplicate of https://github.com/sublimelsp/LSP/issues/1959

LSP is not the one who needs to implement this, 
this would ideally be provided by Sublime.

There is a open feature request for Sublime
https://github.com/sublimehq/sublime_text/issues/1649 here, you can subscribe to it.

**Closed by predragnikolic** 2024-05-29 08:37 UTC

**Comment by silverwind** [comment] 2024-05-29 08:50
Ah, as I suspected, it's an upstream issue. Thanks for the links.
