### ISSUE TITLE
KeyError on file-watcher

### ISSUE THREAD

**Issue by yaroslavyaroslav** [sublimelsp/LSP#2483] opened 2024-05-28 15:46 UTC
**Describe the bug**

Sometimes traceback appears in sublime console.

**To Reproduce**

Actually I'm not sure what's causing this error. Maybe it's some garbage collection on watcher side.
**Expected behavior**

**Screenshots**

```
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/transports.py", line 156, in invoke
    callback_object.on_payload(p)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-file-watcher-chokidar.sublime-package/watcher.py", line 248, in on_payload
KeyError: '71'
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/transports.py", line 156, in invoke
    callback_object.on_payload(p)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-file-watcher-chokidar.sublime-package/watcher.py", line 233, in on_payload
KeyError: '71'
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/transports.py", line 156, in invoke
    callback_object.on_payload(p)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-file-watcher-chokidar.sublime-package/watcher.py", line 248, in on_payload
KeyError: '73'
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/transports.py", line 156, in invoke
    callback_object.on_payload(p)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-file-watcher-chokidar.sublime-package/watcher.py", line 233, in on_payload
KeyError: '71'
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/transports.py", line 156, in invoke
    callback_object.on_payload(p)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-file-watcher-chokidar.sublime-package/watcher.py", line 233, in on_payload
KeyError: '71'
```

**Logs**

I believe this is server agnostic issue.

```
# Troubleshooting: LSP-basedpyright
## Version
 - LSP: 2.1.0
 - Sublime Text: 4175
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}",
  "${server_path}",
  "--stdio"
]
```
 - shell command
```sh
/opt/homebrew/bin/node "/Users/user/Library/Caches/Sublime Text/Package Storage/LSP-basedpyright/21.7.1/language-server/node_modules/basedpyright/langserver.index.js" --stdio
```
 - selector
```
source.python
```
 - priority_selector
```
source.python
```
 - init_options
```json
{}
```
 - settings
```json
{
  "basedpyright": {
    "analysis": {
      "autoImportCompletions": true,
      "autoSearchPaths": true,
      "diagnosticMode": "openFilesOnly",
      "diagnosticSeverityOverrides": {
        "reportAny": "warning",
        "reportDeprecated": "none",
        "reportDuplicateImport": "warning",
        "reportImplicitOverride": "none",
        "reportImplicitStringConcatenation": "warning",
        "reportIncompatibleMethodOverride": "warning",
        "reportMissingParameterType": "none",
        "reportMissingSuperCall": "none",
        "reportOptionalCall": "warning",
        "reportOptionalMemberAccess": "warning",
        "reportOptionalSubscript": "warning",
        "reportUnboundVariable": "none",
        "reportUninitializedInstanceVariable": "none",
        "reportUnknownMemberType": "none",
        "reportUnknownVariableType": "none",
        "reportUnusedClass": "information",
        "reportUnusedFunction": "information",
        "reportUnusedImport": "information",
        "reportUnusedVariable": "information"
      },
      "extraPaths": [],
      "logLevel": "Information",
      "stubPath": "./typings",
      "typeCheckingMode": "all",
      "typeshedPaths": [],
      "useLibraryCodeForTypes": true
    },
    "dev_environment": "sublime_text_38",
    "disableLanguageServices": false,
    "disableOrganizeImports": false
  },
  "python": {
    "pythonPath": "/opt/homebrew/bin/python3",
    "venvPath": "~/.venv/"
  }
}
```
 - env
```json
{
  "PATH": "/opt/homebrew/bin:/opt/homebrew/bin:"
}
```

## Active view
 - File name
```
None
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag | source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc | text.html.markdown meta.link",
  "lsp_active": null,
  "syntax": "Packages/Text/Plain text.tmLanguage"
}
```
 - base scope
```
text.plain
```

## Project / Workspace
 - folders
```json
[
  "/Users/user/Development/git/Swift-Next"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {
    "LSP": {
      "LSP-yaml": {
        "settings": {
          "yaml.format.printWidth": 100
        }
      },
      "SourceKit": {
        "enabled": false
      }
    },
    "ai_assistant": {
      "cache_prefix": "swift_next_project"
    },
    "index_exclude_patterns": [
      "*.swift"
    ],
    "index_files": false,
    "index_workers": 1,
    "lsp_format_on_save": false
  }
}
```

## LSP configuration

```json
{
  "inhibit_snippet_completions": false,
  "inhibit_word_completions": true,
  "initially_folded": [
    "comment"
  ],
  "popup_max_characters_width": 100
}
```
## System PATH
 - /Users/user/.mint/bin
 - /Applications/Sublime Merge.app/Contents/SharedSupport/bin
 - /Applications/Sublime Text.app/Contents/SharedSupport/bin
 - /opt/homebrew/bin
 - /opt/homebrew/sbin
 - /usr/local/bin
 - /System/Cryptexes/App/usr/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
 - /Library/Apple/usr/bin
 - /Applications/Little Snitch.app/Contents/Components
 - /Users/user/.cargo/bin
```

**Environment (please complete the following information):**

- OS: macOS 14.4.1
- Sublime Text version: 4175
- LSP version: 2.1.0
- Language servers used: basedpyright, sourcekit-lsp

**Additional context**

**Comment by predragnikolic** [comment] 2024-05-28 17:10
Duplicate of https://github.com/sublimelsp/LSP-file-watcher-chokidar/issues/7

I will close this one, 
we can continue the discussion in LSP-file-watcher-chokidar.

Does this error happen only when you edit and save files for a Sublime Text package? (Which might cause ST to reload the package and maybe cause this error)

Or does error happen for files in any project?

**Closed by predragnikolic** 2024-05-28 17:10 UTC

**Comment by yaroslavyaroslav** [comment] 2024-05-28 17:18
Yeah, this might be the case, and thanks for highlighting that one
