### ISSUE TITLE
goto diagnostic closes the file on escape

### ISSUE THREAD

**Issue by dten** [sublimelsp/LSP#2324] opened 2023-09-16 15:44 UTC
**Describe the bug**
If i have a file open and use goto diagnostic but change my mind and press escape the file I had open closes.

**To Reproduce**
Open a file with diagnostics
Use goto_diagnostic (f8 if you uncomment the keybinding settings)
See your diagnostics in the selector
Press escape

**Expected behavior**
To just end up back where i started

**Screenshots**
i was in a file and i looked at the diagnostics...

![image](https://github.com/sublimelsp/LSP/assets/1019038/9efe1a12-5b34-4145-b358-9f8e18acd0dd)

and then escape leaves me with no more file

![image](https://github.com/sublimelsp/LSP/assets/1019038/de53ef05-02d7-4442-93b8-5d3effe8cb11)

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Sublime Text version: 4155
- LSP version: 1.25.9
- Language servers used: Vetur

**Additional context**

**Comment by jwortmann** [comment] 2023-09-16 15:53
Closing as duplicate of #2323

**Closed by jwortmann** 2023-09-16 15:53 UTC

**Comment by dten** [comment] 2023-09-16 16:09
thank you :) i did try find but some how didn't spot this the latest issues 😓
