### ISSUE TITLE
`lsp_symbol_definition` does not work if `side_by_side=True` / `SEMI_TRANSIENT` view

### ISSUE THREAD

**Issue by giampaolo** [sublimelsp/LSP#2176] opened 2023-01-23 21:13 UTC
**Describe the bug**
I have 2 key bindings configured:
1) `alt+enter`, which invokes `lsp_symbol_definition` command
2) `ctrl+alt+enter`, which invokes `lsp_symbol_definition` + `side_by_side=True` command

When I navigate my (Python) code by using the first method everything is fine, but when I use `side_by_side=True` LSP will successfully bring me (goto) to the code definition, opening a separate `SEMI_TRANSIENT` view, but when I'm in the `SEMI_TRANSIENT` view I can no longer use these 2 keybindings (aka `lsp_symbol_definition` command longer works). Basically `lsp_symbol_definition` + `side_by_side=True` command only works the first time.

**Environment:**
- OS: Ubuntu 22.04
- Sublime Text version: 4147
- LSP version: 1.21.0
- LSP-pyright version: 1.2.9
- Language servers used: not sure

**Comment by rchl** [comment] 2023-01-23 21:24
Sounds like the issue that was just fixed (worked around) in https://github.com/sublimelsp/LSP/pull/2174. It will be included in the next LSP version.

**Comment by rchl** [comment] 2023-01-23 21:24
Duplicate of https://github.com/sublimelsp/LSP/issues/1979

**Closed by rchl** 2023-01-23 21:24 UTC

**Comment by giampaolo** [comment] 2023-01-23 21:50
Thanks for the quick response @rchl. This package is essential, so I'm glad to see it's so actively and well maintained.
