### ISSUE TITLE
`window.project_data()` may return corrupted data

### ISSUE THREAD

**Issue by koreno** [sublimelsp/LSP#1632] opened 2021-03-31 21:16 UTC
I keep getting this error message in sublime's console:

```
Traceback (most recent call last):
  File "/home/ofer/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/configuration.py", line 80, in _on_done
  File "/home/ofer/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 375, in disable_config
  File "/home/ofer/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 365, in update_configs
  File "/home/ofer/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 109, in update
  File "/home/ofer/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 127, in _create_window_configs
AttributeError: 'str' object has no attribute 'get'
```

**Environment (please complete the following information):**
- OS: Ubuntu 16.04
- Sublime Text version: 3.2.2 Build 3211
- LSP version: v0.14.3
- Language servers used: rust-analyzer

**Comment by rwols** [comment] 2021-04-04 14:32
It's expecting a dictionary whereas you have a string value somewhere in your configuration. Use LSP-json to see what the problem is as it provides schema validation.

**Comment by Phaiax** [comment] 2021-04-14 20:06
Hi.
I have the same problem and managed to track it down a bit.

#### Environment

- Sublime 3.2.2 Build 3211
- OS: Ubuntu 20.04
- LSP verison: v0.14.3 (git clone + git switch 3154-0.14.3 + some debug() statements)
- Language servers used: mun language-server (custom)

(I added a syntax file for mun that is based on the Rust Extended syntax file. That's maybe another similarity of mine and @koreno s environment)

#### Analysis

Backtrace and debug prints (the three most relevant lines are prepended with >>>)
```
LSP: _create_window_configs for {'folders': [{'path': '/home/daniel/Code/mun'}]}
LSP: _on_done index= 13
LSP: _on_done config_name= munls
LSP: _on_done self.window= <sublime.Window object at 0x7fa7eb9e6490>
LSP: _on_done self.window.project_data()= {'folders': [{'path': '/home/daniel/Code/mun'}]}
LSP: _on_done wm= <LSP.plugin.core.windows.WindowManager object at 0x7fa7eb9e6dd0>
LSP: _on_done wm._configs= <LSP.plugin.core.configurations.WindowConfigManager object at 0x7fa7eb9e6390>
LSP: enable_in_project. window= <sublime.Window object at 0x7fa7eb9aa7d0>
>>> LSP: enable_in_project. project_data= {'folders': [{'path': '/home/daniel/Code/mun'}], 'settings': {'LSP': {'munls': {'enabled': True}}}}
>>> LSP: enable_in_project. window.project_data= Packages/User/mun.sublime-syntax
>>> LSP: _create_window_configs for Packages/YAML/YAML.sublime-syntax
Traceback (most recent call last):
  File "/home/daniel/.config/sublime-text-3/Packages/LSP/plugin/configuration.py", line 55, in _on_done
    wm.enable_config(config_name)
  File "/home/daniel/.config/sublime-text-3/Packages/LSP/plugin/core/windows.py", line 369, in enable_config
    self.update_configs()
  File "/home/daniel/.config/sublime-text-3/Packages/LSP/plugin/core/windows.py", line 365, in update_configs
    self._configs.update()
  File "/home/daniel/.config/sublime-text-3/Packages/LSP/plugin/core/configurations.py", line 109, in update
    self.all = self._create_window_configs()
  File "/home/daniel/.config/sublime-text-3/Packages/LSP/plugin/core/configurations.py", line 128, in _create_window_configs
    project_clients_dict = (self._window.project_data() or {}).get("settings", {}).get("LSP", {})
AttributeError: 'str' object has no attribute 'get'

```
The relevant functions with added debug prints:

workspace.py:

```python
def enable_in_project(window: Any, config_name: str) -> None:
    project_data = window.project_data()
    if isinstance(project_data, dict):
        project_settings = project_data.setdefault('settings', dict())
        project_lsp_settings = project_settings.setdefault('LSP', dict())
        project_client_settings = project_lsp_settings.setdefault(config_name, dict())
        project_client_settings['enabled'] = True
        debug('enable_in_project. window=', window)
        debug('enable_in_project. project_data=', project_data)
        window.set_project_data(project_data)
        debug('enable_in_project. window.project_data=', window.project_data())
    else:
        debug('non-dict returned in project_settings: ', project_data)
```

core/configurations.py

```python
    def _create_window_configs(self) -> List[ClientConfig]:
        debug('_create_window_configs for', self._window.project_data())
        project_clients_dict = (self._window.project_data() or {}).get("settings", {}).get("LSP", {})
        return [self._apply_project_overrides(c, project_clients_dict) for c in self._global_configs]
```
In `create_window_configs()`, `window.project_data()` returns a string instead of a dict. I tried to find out where this comes from.

In `enable_in_project()`, window.project_data() is returning a dict. This dict is then modified and set back into the window via `window.set_project_data()`. If I read the project data again directly afterwards, it's suddenly a string. (see debug prints before stack trace).

Is this a reference counting issue in the sublime python api?
I tried 
```
def enable_in_project(window: Any, config_name: str) -> None:
    project_data = window.project_data()
    if isinstance(project_data, dict):
        import copy
        project_data = copy.deepcopy(project_data)
        ...
```
but that did not help.

Or is this a data race with a different sublime package which is also modifying the project settings?
I disabled all packages and it still gave the backtrace from above whenever I tried to enable the LSP.

Then I noticed that I did not have a real sublime project saved, only the folder opened. (There is a rust project in the same folder and the rust language server works without an active sublime-project). So I saved the folder as a project and the error went away. 
Afterwards I tried to recreate the error by opening the folder as a project again. I did not manage to reproduce the error, even after deleting the `.sublime-project` and `.sublime-workspace` files. The debug statements still showed the project_data() magickly becoming a string.

Then I added the following debug statements:
```
def enable_in_project(window: Any, config_name: str) -> None:
    project_data = window.project_data()
    if isinstance(project_data, dict):
        import copy
        project_data = copy.deepcopy(project_data)
        project_settings = project_data.setdefault('settings', dict())
        project_lsp_settings = project_settings.setdefault('LSP', dict())
        project_client_settings = project_lsp_settings.setdefault(config_name, dict())
        project_client_settings['enabled'] = True
        debug('enable_in_project. window=', window)
        debug('enable_in_project. project_data=', project_data)
        window.set_project_data(project_data)
        debug('enable_in_project. window.project_data=', window.project_data())
        debug('enable_in_project. window.project_data=', window.project_data())
        debug('enable_in_project. window.project_data=', window.project_data())
        debug('enable_in_project. window.project_data=', window.project_data())

```

This generates the following output:
```
LSP: enable_in_project. window= <sublime.Window object at 0x7f752b83d5d0>
LSP: enable_in_project. project_data= {'settings': {'LSP': {'munls': {'enabled': True}}}, 'folders': [{'path': '/home/daniel/Code/mun'}]}
LSP: enable_in_project. window.project_data= Packages/User/mun.sublime-syntax
LSP: enable_in_project. window.project_data= {'settings': {'LSP': {'munls': {'enabled': True}}}, 'folders': [{'path': '/home/daniel/Code/mun'}]}
LSP: enable_in_project. window.project_data= {'settings': {'LSP': {'munls': {'enabled': True}}}, 'folders': [{'path': '/home/daniel/Code/mun'}]}
LSP: enable_in_project. window.project_data= {'settings': {'LSP': {'munls': {'enabled': True}}}, 'folders': [{'path': '/home/daniel/Code/mun'}]}
```

The first `.project_data()` returns the string, and the second one returns the dict we set before.
Seems like a sublime bug to me.

Ah, more interesting observations:
When I have another file with a different syntax open, the calls to `project_data()` seem to cycle through the syntax files off all open files. That could explain why I could not reproduce the error after going back to the not-a-project type. I did have less files open in that window, so less calls to `project_data()` were corrupted. --> Yes, after removing the additional calls to `project_data()` I can reprocude the above backtrace again. And with this knowledge I can even reproduce it if I open the folder as a sublime project. I only need to have enough other files open.

```
LSP: enable_in_project. project_data= {'settings': {'LSP': {'munls': {'enabled': True}}}, 'folders': [{'path': '/home/daniel/Code/mun'}]}
LSP: enable_in_project. window.project_data= Packages/User/mun.sublime-syntax
LSP: enable_in_project. window.project_data= Packages/YAML/YAML.sublime-syntax
LSP: enable_in_project. window.project_data= {'settings': {'LSP': {'munls': {'enabled': True}}}, 'folders': [{'path': '/home/daniel/Code/mun'}]}
```

This are the loaded plugins when this happened:
```
startup, version: 3211 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/daniel/.config/sublime-text-3/Packages
state path: /home/daniel/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/daniel/.config/sublime-text-3/Installed Packages
ignored_packages: ["CSS", "Diff", "Dockerfile Syntax Highlighting", "HTML", "LSP-json", "LuaFormat", "Pretty JSON", "Python 3", "Rust", "Rust Enhanced", "SCSS", "ShellScript", "Sonic Pi", "Vintage"]
pre session restore time: 0.161578
startup time: 0.2822
git: tracking working dir /home/daniel/.config/sublime-text-3/Packages/LSP
first paint time: 0.333817
git: tracking working dir /home/daniel/Code/mun/game
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-sublime_lib
reloading plugin 0_package_control_loader.10-lsp_utils
reloading plugin 0_package_control_loader.10-shellenv
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin LSP.boot
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
```

**Comment by rwols** [comment] 2021-11-05 20:53
Supposedly fixed in ST dev build 4122.

**Closed by rwols** 2021-11-05 20:53 UTC
Labels: sublime issue
