### ISSUE TITLE
On Windows, the drive letter in server responsed file URIs are lowercase.

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP#1770] opened 2021-06-30 12:43 UTC
**Describe the bug**

I tried both intelephense and pyright, they both returned lowercased drive letter thus I suspect it's a standard. (or maybe VSCode's LSP lib does it)

https://user-images.githubusercontent.com/6594915/123961095-96286c80-d9e2-11eb-8ada-0da9af754a55.mp4

In "Goto Definition...", this causes ST to open a file whose drive letter is in lowercase. And that may cause various mysterious problem sometimes... Or maybe, this should be fixed in ST core.

**To Reproduce**
1. Install LSP-intelephense with a Windows build ST
2. Open a PHP project
3. Make sure the definition file is not opened in a tab already
4. Do "Goto Definition"
5. The newly opened tab should have a lower drive letter

**Expected behavior**

The drive letter should be uppercase.

**Environment (please complete the following information):**
- OS: Win10 21H1 x64
- Sublime Text version: 4109
- LSP version: 4070-1.6.1
- Language servers used: intelephense, pyright

**Additional context**

This is a Windows-only issue as it's case-insensitive.

**Comment by rwols** [comment] 2021-06-30 20:53
> The drive letter should be uppercase.

Why?

**Comment by jfcherng** [comment] 2021-06-30 22:21
> > The drive letter should be uppercase.
> 
> Why?

Because it's Windows' default, unless the user somehow uses lowercase intentionally.

**Comment by jwortmann** [comment] 2021-07-01 15:16
There is another problem with the lowercase drive letters when opening a file: even though Sublime highlights the correct file in the sidebar (if it is a file from an opened folder), it doesn't it doesn't show the git status in the status bar for files with lowercase drive letter (if it is part of a git repo). So we should normalize the drive letter to uppercase.

**Comment by jwortmann** [comment] 2021-07-01 16:48
Another thing that doesn't work as intended is the quick panel for "Find References" if *"show_references_in_quick_panel"* is `true` in LSP settings. It shows the full path, but without drive letter (i.e. starting with `:`). That seems to happen because `os.path.commonprefix((pathname, base_dir))` called in `location_to_human_readable` is an empty string (base_dir has uppercase drive letter and pathname has lowercase drive letter). I already have a fix to normalize to uppercase drive letter in `uri_to_filename` in core/url.py (that function is marked as deprecated though).

And I think I've found another bug (?) in https://github.com/sublimelsp/LSP/blob/ef40138111ad47b492139134f66cc7e96b95224e/plugin/core/url.py#L24
this line does nothing because the return value is not assigned to a variable (strings are immutable in Python afaik).

**Closed** 2021-07-01 20:59 UTC

**Comment by jfcherng** [comment] 2021-07-01 21:32
Awesome! Confirm fixed on my side as well. Thanks!
