### ISSUE TITLE
setting `"mdpopups.use_sublime_highlighter": false` causes popups to crash and never render

### ISSUE THREAD

**Issue by dmilith** [sublimelsp/LSP#1579] opened 2021-02-13 09:23 UTC
**Describe the bug**
A console dump should be sufficient:

```
Traceback (most recent call last):
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/hover.py", line 150, in <lambda>
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/hover.py", line 153, in _show_hover
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/hover.py", line 147, in hover_content
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 450, in minihtml
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 441, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"')
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/core.py", line 265, in convert
    self.lines = prep.run(self.lines)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 737, in run
    return self.search_nested(lines)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 601, in search_nested
    self.eval_fence(ws, content, start, end)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 407, in eval_fence
    self.process_nested_block(ws, content, start, end)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 451, in process_nested_block
    code = entry["formatter"](self.rebuild_block(self.code), self.lang, self.options, self.md)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 666, in highlight
    linespecial=linespecial
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 450, in highlight
    code = highlight(src, lexer, formatter)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/formatters/html.py", line 831, in format_unencoded
    source = self.wrap(source, outfile)
  File "/Users/dmilith/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 281, in wrap
    return self._wrap_code(self, source)
TypeError: _wrap_code() takes 2 positional arguments but 3 were given
```

**To Reproduce**
1. Change `"mdpopups.use_sublime_highlighter": false` in ST4 configuration
2. Use `lsp_hover` functionality
3. See error in console

**Expected behavior**
Well, popup should show :)

**Screenshots**
None

**Environment (please complete the following information):**

    OS: macOS 11.2.1
    Sublime Text version: [build 4098]
    LSP version: 1.2.10 (latest)
    Language servers used: rust-analyzer (last non-nightly build available)

**Additional context**
None

**Comment by rwols** [comment] 2021-02-13 09:24
duplicate of https://github.com/facelessuser/sublime-markdown-popups/issues/110

cc @facelessuser

**Closed by rwols** 2021-02-13 09:24 UTC
