### ISSUE TITLE
Completion prefix not removed properly on completing fast

### ISSUE THREAD

**Issue by ryanpcmcquen** [sublimelsp/LSP#1248] opened 2020-08-11 23:35 UTC
![weird_completion](https://user-images.githubusercontent.com/772937/89959117-80566100-dbf0-11ea-8094-d119addff58b.gif)

Please include in your report:

* Mac OS / LSP-intelephense / Sublime Text 4 (4081)
* Installed from Package Control
* Type a statement (like `$foo = 'bar';`, then go back to add a function to wrap `'bar'`, like `json_decode`), notice that part of the completion prefixes the full completion, ending up with something like:
```
son_djson_decode
```

I haven't been able to reproduce it again to get a log, but when I do I will be sure to attach that as well. It has happened several times over the past few days.

**Comment by ryanpcmcquen** [comment] 2020-08-12 18:30
Yay, got the log!

```
IndexError
Unable to open /Users/rmcquen/Library/Application Support/Sublime Text 3/Packages/LSP/LSP.sublime-settings
reloading settings Packages/User/LSP.sublime-settings
Unable to open /Users/rmcquen/Library/Application Support/Sublime Text 3/Packages/LSP/LSP.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 846, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/AutoFileName.sublime-package/autofilename.py", line 162, in on_modified
    sel = view.sel()[0].a
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 854, in on_selection_modified
    run_view_callbacks('on_selection_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/Persistent Status Bar Line Number.sublime-package/persistent_status_bar_line_number.py", line 8, in on_selection_modified
    view.sel()[0].begin()
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 846, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/AutoFileName.sublime-package/autofilename.py", line 162, in on_modified
    sel = view.sel()[0].a
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 854, in on_selection_modified
    run_view_callbacks('on_selection_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/Persistent Status Bar Line Number.sublime-package/persistent_status_bar_line_number.py", line 8, in on_selection_modified
    view.sel()[0].begin()
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 846, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/AutoFileName.sublime-package/autofilename.py", line 162, in on_modified
    sel = view.sel()[0].a
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 854, in on_selection_modified
    run_view_callbacks('on_selection_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/Persistent Status Bar Line Number.sublime-package/persistent_status_bar_line_number.py", line 8, in on_selection_modified
    view.sel()[0].begin()
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 846, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/AutoFileName.sublime-package/autofilename.py", line 162, in on_modified
    sel = view.sel()[0].a
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1381, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1072, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 854, in on_selection_modified
    run_view_callbacks('on_selection_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 665, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 147, in profiler
    return event_handler(*args)
  File "/Users/rmcquen/Library/Application Support/Sublime Text 3/Installed Packages/Persistent Status Bar Line Number.sublime-package/persistent_status_bar_line_number.py", line 8, in on_selection_modified
    view.sel()[0].begin()
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 846, in __getitem__
    raise IndexError()
IndexError
```

**Comment by rchl** [comment] 2020-08-12 18:44
There seems to be something really wrong with your ST if you are getting errors like
```
Unable to open /Users/rmcquen/Library/Application Support/Sublime Text 3/Packages/LSP/LSP.sublime-settings
```
Also notice that all of those stack traces are related to other packages.

**Comment by ryanpcmcquen** [comment] 2020-08-12 18:47
I am on ST4.

**Comment by rchl** [comment] 2020-08-12 18:47
Actually that might not be a problem. It probably means that you've opened LSP settings and you don't have any customizations.
But all in all none of that seems related to your original issue.

**Comment by ryanpcmcquen** [comment] 2020-08-12 18:55
Yeah, I can't get anything useful from the log but I am repro-ing the issue semi regularly. Here's my full package list if it helps:

```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"AutoFileName",
		"AutoPEP8",
		"Babel",
		"Clang Format",
		"DashDoc",
		"Debugger",
		"DiffTabs",
		"Dockerfile Syntax Highlighting",
		"DotENV",
		"DoxyDoxygen",
		"EditorConfig",
		"FileDiffs",
		"fish",
		"Function Name Display",
		"Gremlins",
		"JsPrettier",
		"LSP",
		"LSP-intelephense",
		"LSP-typescript",
		"MarkdownPreview",
		"Nord",
		"Package Control",
		"Persistent Status Bar Line Number",
		"PHP-Twig",
		"RawLineEdit",
		"RESTer HTTP Client",
		"RustFmt",
		"Sass",
		"SendToPasteBin",
		"StandardFormat",
		"SublimeLinter",
		"SublimeLinter-contrib-phpstan",
		"SublimeLinter-contrib-standard",
		"SublimeLinter-php",
		"Terminus",
		"uroboroSQL Formatter",
		"Witness color scheme",
	],
	"repositories":
	[
	],
}
```

**Comment by rchl** [comment] 2020-08-30 19:12
Can't reproduce this one. Neither with intelephense nor with my simple plugin based on @rwols' payloads: https://gist.github.com/rchl/721c69ab2a01794f07a48841828605df

If it's an actual ST bug, we should find a way to reproduce and submit an issue.

**Comment by predragnikolic** [comment] 2020-09-10 13:44
I think that the COMPLETION_FLAG_KEEP_PREFIX flag is not working correctly in the later ST builds.
I tried ST 4085 and 4083 and I can reproduce the issue with LSP-elm:

![output](https://user-images.githubusercontent.com/22029477/92738667-6ee1af80-f37c-11ea-9440-73916198e7c7.gif)

**Comment by rchl** [comment] 2020-09-10 14:14
Can you post logs? We still don't have a reliable way to reproduce.

**Comment by predragnikolic** [comment] 2020-09-10 15:45
here are my logs, that should be simpler to follow. I added 4 print statements,
1. When sending the completion request.
2. When receiving the completion response.
3. When selecting the completion item.
4. When we notify the server of a change event

This bug only occurs when we **select** the completion item before we **receive** the response for the last request.

```
notify did change
notify did change
notify did change
send completions request 2
receive response 2
notify did change
send completions request 3
selected item {'textEdit': {'newText': 'Image', 'range': {'end': {'line': 0, 'character': 6}, 'start': {'line': 0, 'character': 5}}}, 'kind': 20, 'label': 'Image', 'sortText': 'b_Image'}
receive response 3
notify did change
```

![b4083](https://user-images.githubusercontent.com/22029477/92756676-51691180-f38d-11ea-95d4-82ea001b54da.gif)


If we select the completion item after we receive the last completion response,
everything works as expected.

```
notify did change
send completions request 4
receive response 4
notify did change
selected item {'textEdit': {'newText': 'Image', 'range': {'end': {'line': 0, 'character': 7}, 'start': {'line': 0, 'character': 5}}}, 'kind': 20, 'label': 'Image', 'sortText': 'b_Image'}  // this is ok, we selected the completion item after we received the last completion response
notify did change
```

**Comment by rchl** [comment] 2020-09-10 15:47
I was thinking LSP logs :).
Are those completions returned with dynamic completions flag?

**Comment by predragnikolic** [comment] 2020-09-10 16:04
I can reproduce the issue even without the dynamic flag. 

Let me breakdown what I think is going on.

send completions request 2  // ST Sets the KEEP PREFIX - (prefix == 'I')
```
1|type I|
```

receive response 2          // received CompletionItems for request 2
```
1|type I|
       ___________
       | Image
       |
```

notify did change           // continue typing to trigger a new completion request
```
1|type Ima|
       ___________
       | Image
       |
```

send completions request 3  // ST Sets the KEEP PREFIX for completions request 3, (prefix == 'Ima')


selected item               // but we immediately select the completion item that was received from request 2 
```
    {'textEdit': {'newText': 'Image', 'range': {'end': {'line': 0, 'character': 6}, 'start': {'line': 0, 'character': 5}}}, 'kind': 20, 'label': 'Image', 'sortText': 'b_Image'}
```

So what happens is the following.
ST leaves the prefix newest prefix (that was set for request 3, but we selected a completion item recieved from request 2), 
which in this case is 'Ima' (prefix == 'Ima') which is the wrong prefix for the request 2. 
For the request 2 I expect the Keep prefix to be "I".

So ST leaves the prefix "Ima" and we apply the text edit which leaves us with the following state:
```
1|type Imagema|
```


receive response 3          // we receive the response for request 3
notify did change

**Comment by rchl** [comment] 2020-09-10 16:14
The thing is, only one completion request is normally triggered in such a cases - only with dynamic flag completions are requested for each keystroke. If you are getting multiple completion requests without dynamic flag then that's the root issue most likely.

And it's like to know how to reproduce that so that we can create minimal test case.

**Comment by predragnikolic** [comment] 2020-09-10 17:08
> **only** with dynamic flag completions are requested for each keystroke

Even without the dynamic flag, the `on_query_completions` is called on each keystroke. (which means that we send the completion on each keystroke). 

Correct me if I am wrong, the DYNAMIC_COMPLETIONS is used by ST to update the completion items in the AC popup when ST is already showing the AC popup. (We use it in LSP when isIncoplete is true, so we don't have to hide and show the AC to make the new Completion items visible in the AC popup)

**Comment by rchl** [comment] 2020-09-10 17:17
> Even without the dynamic flag, the `on_query_completions` is called on each keystroke. (which means that we send the completion request on each keystroke).

Well, that's not right then. :)

I wonder if this looks any special:
```
view.settings().get('auto_complete_selector')
```
If it's not that probably you are the only one that can figure it out as it's not normal behavior that happens with all files and servers. Maybe some other installed package affects it? Can you reproduce in safe mode with just a bare minimum of packages installed?

**Comment by predragnikolic** [comment] 2020-09-10 18:16
I was wrong, I was pretty certain that the on_query_completion was called on each keystroke without the flag. It is not.

>  only with dynamic flag completions are requested for each keystroke

This here is correct.

**Comment by rchl** [comment] 2020-09-10 18:50
Just to clarify: so all your results were with `DYNAMIC_COMPLETIONS` flag set?

**Comment by predragnikolic** [comment] 2020-09-10 19:01
> Just to clarify: so all your results were with DYNAMIC_COMPLETIONS flag set?

Yes, 

but even if I remove this code, I can still reproduce the [issue](https://github.com/sublimelsp/LSP/issues/1248#issuecomment-690380031) that you saw in the gif above.
```diff
             response_items = response["items"] or []
-            if response.get("isIncomplete", False):
-                flags |= sublime.DYNAMIC_COMPLETIONS
```

**Comment by rchl** [comment] 2020-09-10 19:05
In that case, maybe you can figure out why it's the case.
 - what's the view settings I've asked about before?
 - does it happen on any file?
 - does it happen with any server?
 - does it reproduce in safe mode with minimum number of packages installed

**Comment by predragnikolic** [comment] 2020-09-10 19:27
* what's the view settings I've asked about before?
```
>>> view.settings().get('auto_complete_selector')
'meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc'
```

* does it happen on any file?
yes I can reproduce it with any elm file. I just need to type really fast and commit the completion. But 90% of the time the AC works correctly... There is this 10% where I can successfully trigger this bug.
 
* does it happen with any server?
I tried with intelephense the [example](https://github.com/sublimelsp/LSP/issues/1248#issue-677266844), but I cannot reproduce it. I can only reproduce it with elm right now.

 * does it reproduce in safe mode with minimum number of packages installed?
Can I even test this in safe mode? For example when I install LSP in ST --safe-mode, don't the LSP dependencies require a reload of st when I do Package Control: Satisfy Dependecies?

**Comment by rchl** [comment] 2020-09-10 20:38
> view.settings().get('auto_complete_selector')

Sorry, I meant `auto_complete_triggers`. But probably it's a dead-end anyway.

> Can I even test this in safe mode?

I guess it might be tricky. But since you are on Linux it should be pretty easy to test by creating a separate, clean profile (or rename the main one for testing).

I've tried with LSP-elm and can't reproduce here. It doesn't even use `isIncomplete: true` by default which I had impression it does for you.

**Comment by rwols** [comment] 2020-09-14 07:32
The new alpha build 4086 mentions fixes relating to the prefix removal. Perhaps this is now fixed?

**Comment by predragnikolic** [comment] 2020-09-14 09:40
I can confirm that it is fixed with ST build 4086

**Closed** 2020-09-14 09:39 UTC
