### ISSUE TITLE
Large error/warning scopes make files unreadable

### ISSUE THREAD

**Issue by kornelski** [sublimelsp/LSP#1709] opened 2021-05-31 10:35 UTC
**Describe the bug**
rust-analyzer has an [inactive code](https://rust-analyzer.github.io/manual.html#inactive-code) and similar warnings that apply to potentially large blocks of code. In Sublime Text 4 this results in every line being underlined. The underlines are very distracting, and make it hard to work on the file.

**To Reproduce**
1. Install Rust via rustup, enable rust-analyzer.
2. `cargo new foo`
3. In `foo/src/main.rs` add:

```rust
#[cfg(feature = "off")] 
fn foo() { 
	"imagine lots of code here"; 
}
```

**Expected behavior**
It would be nice if a large scope like this could be marked less obtrusively, e.g. in the sidebar, or only on the first and last line of the scope.

**Screenshots**
![underline bonanza](https://user-images.githubusercontent.com/72159/120180767-156c2a00-c204-11eb-866b-bda0fd448f19.png)

**Environment (please complete the following information):**
- OS: macOS 11
- Sublime Text version: 4107
- LSP version: 1.4.0
- Language servers used: rust-analyzer

**Comment by rwols** [comment] 2021-05-31 16:39
Thanks for the heads up. This is a duplicate of https://github.com/sublimelsp/LSP/issues/1547.

**Closed by rwols** 2021-05-31 16:39 UTC

**Comment by predragnikolic** [comment] 2021-05-31 21:45
FWIW I installed rust-analyzer-preview on Windows 10 via rustup.
Apparently on newer versions of rust-analyzer I cannot reproduce this.

![last commit](https://user-images.githubusercontent.com/22029477/120244226-f6a07e80-c269-11eb-9d03-f1d8aae3f30f.png)

**Comment by kornelski** [comment] 2021-05-31 21:56
Indeed, the latest version of rust-analyzer has added a workaround for the unlinked-file diagnostic, and they've changed the span to be only the first line.

However, the problem remains for the inactive-code diagnostic. I don't understand why you're getting unlinked-file about `main.rs` — that file shouldn't be possible to be unlinked.
