### ISSUE TITLE
Increase the delay of checking

### ISSUE THREAD

**Issue by kud** [sublimelsp/LSP#1089] opened 2020-06-03 14:27 UTC
Hello,

It could be great to increase (or let the user decide) the delay of checking, because right now, having an kind of instant feedback when you're typing your code is quite disturbing for me/my eyes.

I would like to have a feedback when nothing happens (no type, like a debounce) after 2s for instance.

Thank you!

tl;dr: start checking after 2s using debounce.

**Comment by predragnikolic** [comment] 2020-06-03 15:40
![image](https://user-images.githubusercontent.com/22029477/83657228-dbe8ea80-a5c0-11ea-8a1e-c2df4d061add.png)

Related feedback from discord

**Comment by Gotterbild** [comment] 2020-06-12 20:16
Agree. Debounce is a must have. Actually, I was surprised I didn't find the item in settings for that. 

I work with larger projects that run inside Docker container. And when I do it on my laptop somewhere outside, the lack of debounce extensively uses CPU, which drains battery and sometimes overheats my laptop and it starts to throttle. And I definitely can tell the LSP is the cause because when I disable it, the laptop overheats and throttles way less often and lives longer, sometimes significantly.

**Comment by kud** [comment] 2020-06-12 20:23
IMO it should be indeed a setting.

**Comment by rwols** [comment] 2020-06-12 20:37
> I work with larger projects that run inside Docker container. And when I do it on my laptop somewhere outside, the lack of debounce extensively uses CPU, which drains battery and sometimes overheats my laptop and it starts to throttle. And I definitely can tell the LSP is the cause because when I disable it, the laptop overheats and throttles way less often and lives longer, sometimes significantly.

We can delay the *presentation* of diagnostics, but not the *computation* of diagnostics, as that's done by your language server. An editor doesn't have control over that.

**Comment by kud** [comment] 2020-06-12 21:30
To my position, it's already a good thing because I don't like having some blink effect when I type my code. It's like "wow calm down, I didn't finish my sentence, don't interrupt me" :D

**Comment by rwols** [comment] 2020-07-15 17:48
Fixed in #1170 (but only for ST4).

The defaults are 0 milliseconds to preserve the old behavior. But you can increase the delay.

**Closed by rwols** 2020-07-15 17:48 UTC
Labels: enhancement
