### ISSUE TITLE
Code actions might not trigger when there are multiple sessions with the same config name

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1084] opened 2020-06-01 20:45 UTC
If the document has multiple sessions for the same config name (for example `lsp-stylelint` running both for the `text.html.vue` and `source.scss` scopes in a `vue` file) then the code-actions-collecting-code gets confused and never calls the handler callback.

This is due to keying results by config name and in this case, both sessions have the same config name.

I'm currently in ST3 and see the problem there but it should also affect ST4 judging from the code being more or less the same there.

**Comment by rchl** [comment] 2020-06-01 21:12
Know that I think about it, the issue is specific to CAOS PR.

The none-CAOS  code will skip results from one of those sessions though. Which in practice might be ok, depending on the user case.

The case of two sessions running same server, in the same document, is a bit tricky to wrap the head around and would have to be investigated. It might make sense to somehow collapse such sessions.

**Comment by rwols** [comment] 2020-06-02 08:49
> The case of two sessions running same server, in the same document, is a bit tricky to wrap the head around and would have to be investigated.

It's impossible and not allowed by design.

> If the document has multiple sessions for the same config name (for example lsp-stylelint running both for the text.html.vue and source.scss scopes in a vue file)

Can you explain what you mean here? A document/view cannot have two sessions with the same name.

**Comment by rwols** [comment] 2020-06-02 09:20
Are you perhaps talking about the `feature_selector` (old: `scopes`) ?

**Comment by rchl** [comment] 2020-06-02 09:26
> Can you explain what you mean here? A document/view cannot have two sessions with the same name.

It doesn't seem like that can happen in LSP4 but it does in LSP3.
In my case, I can see it with workspace-less setup at leats, in `vue` files.

When logging sessions returned with `sessions_for_view` in `request_code_actions_with_diagnostics` I get:
```
  lsp-stylelint
   ['source.scss'] ['Packages/Sass/Syntaxes/SCSS.sublime-syntax']
   ['source.css'] ['Packages/Sass/Syntaxes/CSS.sublime-syntax']
   ['text.html.vue'] ['Packages/Vue Syntax Highlight/Vue Component.sublime-syntax']
  lsp-stylelint
   ['source.scss'] ['Packages/Sass/Syntaxes/SCSS.sublime-syntax']
   ['source.css'] ['Packages/Sass/Syntaxes/CSS.sublime-syntax']
   ['text.html.vue'] ['Packages/Vue Syntax Highlight/Vue Component.sublime-syntax']
```
These are two separate sessions and their respective configs.

**Comment by rchl** [comment] 2020-06-02 09:30
Actually it might be related to also having `lsp-eslint` enabled.
I think there is some kind of issue there but I'm not sure I want to investigate it as it seems to be LSP3-only issue.

**Comment by rchl** [comment] 2020-06-02 09:43
So, based on master branch...
This line in `registry.py`:
```py
scope_configs = manager._configs.scope_configs(view, point)
```
can return multiple configs with the same name but different scores (due to there being two different matching scopes at a given point):
```
[('lsp-stylelint', 128), ('lsp-stylelint', 24)]
```
Then the next line:
```py
sessions = (manager.get_session(config.name, file_path) for config in scope_configs)
```
will return session for each of those configs. Those will actually be the same sessions, just duplicated.

**Comment by rchl** [comment] 2020-06-02 09:47
(So then it is a bug for master branch after all, not only in CAOS)

**Comment by rwols** [comment] 2020-06-02 17:44
Since it's fixed in the st4 branch, I consider it fixed then :)

**Closed by rwols** 2020-06-02 17:44 UTC
