### ISSUE TITLE
Globally enabled LSP not available for cloned views

### ISSUE THREAD

**Issue by jakebowkett** [sublimelsp/LSP#1538] opened 2021-01-01 21:09 UTC
Opening single or multiple source files works fine but LSP is not active for cloned files (i.e.,the same file in a different view).

- I have LSP enabled globally.
- LSP appears in the status bar for non-cloned views but for the cloned ones it's absent.
- Non-cloned views continue to work fine.
- I cannot enable the particular language server I'm using (gopls) for the cloned files because it's already enabled.

To reproduce just open a file, clone it, and attempt something LSP should do. Thanks.

**Comment by rwols** [comment] 2021-01-03 17:03
Please report what LSP version you're running and which ST build version you're running.

**Comment by jakebowkett** [comment] 2021-01-03 23:34
ST 3.2.2 (build 3211).

Had trouble finding the LSP version. When I bring up 'Package Control: Remove Package' and look at LSP it says v0.14.3, which seems out of sink with numbers I'm seeing on this repo - not sure if that's right? When I choose 'Package Control: Upgrade Package' it says there are no packages to upgrade.

I initially installed LSP via Package Control, as instructed by README.md

**Comment by rwols** [comment] 2021-01-04 00:15
> seems out of sync with versions I'm seeing on this repo

Versioning is all working as intended -- you're using ST3 so Package Control downloads v0.14.3 of LSP. The ST4 variant is at v1.2.6.

Given that you're using ST3, I don't see me fixing this personally. But you are free to submit a pull request to fix it for ST3. The ST4 variant has this fixed in the case where the view is not semi-transient. If the view is semi-transient, then LSP won't start as well. We could consider this a feature request to attach language servers to semi-transient views as well.

**Closed** 2021-05-28 20:58 UTC
Labels: ST3, wontfix
