### ISSUE TITLE
erase_regions causes "markup.unnecessary.lsp" to flicker

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#2272] opened 2023-05-17 19:23 UTC
**Describe the bug**

**To Reproduce**
1. Run Customize Color scheme from the command palette:
2. Paste this
```
{
    "rules": [
        {
            "scope": "markup.unnecessary.lsp",
            "foreground_adjust": "l(- 40%)",
            "background": "#00000001"
        },
    ]
}
```
4. Open a `hello.vue` file, that looks like this
```
<script setup lang="ts">
let xas = 312

asdaaasssdsasdasd // type here and see the flicker 

</script>
```
6. Type where the `asdaaasssdsasdasd` string is
7. See flicker

**Expected behavior**
There should be no flicker.

**Screenshots**

![output](https://github.com/sublimelsp/LSP/assets/22029477/de824d96-e361-47a9-b2b9-e94dfd859875)

This cannot be reproduced in all vue/ts files, 
only in certain fails like the one I provided.

----

#### Solution

I solved the problem by modifying this function,
but don't know if you guys have a better suggestion.
![2023-05-17-212104_855x298_scrot](https://github.com/sublimelsp/LSP/assets/22029477/679297ec-da7f-4afa-b586-96888f6aea73)

![output](https://github.com/sublimelsp/LSP/assets/22029477/d1e0d279-ed9d-4b91-8699-5b506317dabe)

**Comment by rchl** [comment] 2023-05-17 20:58
This suggested fix might not be 100% correct (even if it might be in practice) because in theory there could exist a tag in `regions_with_tag` but we would not create region for it due to being filtered out due to severity check.

But I see if I can come up with some fix for this.

**Comment by rchl** [comment] 2023-05-17 21:22
It doesn't quite reproduce here for me you can try #2274.

**Closed** 2023-05-18 10:27 UTC
