### ISSUE TITLE
Ignored LSP disabled on project switch 

### ISSUE THREAD

**Issue by psydvl** [sublimelsp/LSP#1996] opened 2022-07-16 15:41 UTC
**Describe the bug**
I have LSP-gopls disabled globally
<details>
<summary>And disabled in project (let's name it project A for this issue)</summary>

``` json
{
	"folders": [
		...
	],
	"settings": {
		"LSP": {
			"LSP-gopls": {
				"enabled": false,
			},
			"gopls":
			{
				"enabled": false
			},
		},
	},
}
```
</details>
And I have another project [B] with gopls enabled
On project switch from B to A gopls start evaluating A files  
<br>
<br>

**To Reproduce**

0. Add big modules enough go project A and any go project B
	(for A you can use mine https://github.com/psydvl/gotk4-template; gopls will take time with gtk4 bindings)
2. Disable LSP-gopls globally
3. Disable LSP-gopls in project A
4. Enable LSP-gopls in project B
5. Open project B
6. Switch to project A
7. Look into any process utility and see gopls keep working (and processing project A files, ps -p $pid -o cmd shows, that processed mod file is related to project A) 

**Expected behavior**
gopls don't even touch project A files

**Environment (please complete the following information):**
- OS: [openSUSE Tumbleweed 20220709-0]
- Sublime Text version: [4126]
- LSP version: [1.16.3]
- Language servers used: [gopls, json]

**Additional context**

<details>
<summary>Troubleshooting: LSP-gopls</summary>

# Troubleshooting: LSP-gopls
## Version
 - LSP: 1.16.3
 - Sublime Text: 4126
## Server Test Run
 - exit code: -1
 - output
```
neither "command" nor "tcp_port" is provided; cannot start a language server
```
## Server Configuration
 - command
```json
[]
```
 - shell command
```sh

```
 - selector
```

```
 - priority_selector
```

```
 - init_options
```json
{}
```
 - settings
```json
{}
```
 - env
```json
{}
```

## Active view
 - File name
```
/home/nixi/work/Projects/Mine/HackerNews/main.go
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Go/Go.sublime-syntax"
}
```
 - base scope
```
source.go
```

## Project / Workspace
 - folders
```json
[
  "/home/nixi/work/Projects/Mine/GLauncher", 
  "/home/nixi/work/Projects/Mine/gotk4-template", 
  "/home/nixi/work/Projects/Mine/HackerNews"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "path": "/home/nixi/work/Projects/Mine/GLauncher"
    }, 
    {
      "path": "/home/nixi/work/Projects/Mine/gotk4-template"
    }, 
    {
      "path": "/home/nixi/work/Projects/Mine/HackerNews"
    }
  ], 
  "settings": {
    "LSP": {
      "LSP-gopls": {
        "enabled": false
      }, 
      "gopls": {
        "enabled": false
      }
    }
  }
}
```

## LSP configuration

```json
{
  "clients": {
    "gopls": {
      "env": {
        "PATH": "/home/nixi/go/bin"
      }
    }
  }, 
  "inhibit_snippet_completions": true, 
  "inhibit_word_completions": true, 
  "log_debug": true, 
  "show_references_in_quick_panel": true
}
```
## System PATH
 - /home/nixi/go/bin
 - /home/nixi/miniconda3/condabin
 - /home/nixi/.nix-profile/bin
 - /nix/var/nix/profiles/default/bin
 - /home/nixi/.local/bin
 - /usr/local/bin
 - /usr/bin
 - /bin

</details>

**Comment by predragnikolic** [comment] 2022-08-10 12:37
I cannot reproduce this with LSP-typescript or LSP-go. 
LSP version 1.17.0
Sublime Text version: [4134]

B.sublime-project looks like this:
```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"LSP-typescript": {
				"enabled": true
			},
			"gopls": {
				"enabled": true
			}
		}
	}
}

```

A.project-settings look like this:
```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"LSP-typescript": {
				"enabled": false
			},
			"gopls": {
				"enabled": false
			}
		}
	}
}

```
//LSP-gopls.sublime-settings looks like this:

{
	"enabled": false
}
```

**Comment by predragnikolic** [comment] 2022-08-19 18:45
I tired this on Linux, cannot reproduce.
I tired with LSP v1.16.3, cannot reproduce.

**Comment by predragnikolic** [comment] 2022-08-20 13:17
I will close this because I cannot repro this.

If you have https://packagecontrol.io/packages/LSP-gopls installed,
The only thing I see as potential probles is the project configuration and LSP configuration.

1. You have a key `"LSP-gopls"` in your project data,
the LSP-gopls plugin, will accept only  "gopls" in sublime project setting. (you will see that if you trigger auto-complete with LSP-json in a sublime project file)

```diff
{
  "folders": [
    {
      "path": "/home/nixi/work/Projects/Mine/GLauncher"
    }, 
    {
      "path": "/home/nixi/work/Projects/Mine/gotk4-template"
    }, 
    {
      "path": "/home/nixi/work/Projects/Mine/HackerNews"
    }
  ], 
  "settings": {
    "LSP": {
-      "LSP-gopls": {
-        "enabled": false
-      }, 
      "gopls": {
        "enabled": false
      }
    }
  }
}
```
2. If you install LSP-* plugins, like in this case LSP-gopls, 
It is not expected to modify LSP-gopls settings in LSP Configuration, 
so this should be removed.
```diff
{
  "clients": {
-    "gopls": {
-      "env": {
-        "PATH": "/home/nixi/go/bin"
-      }
    }
  }, 
  "inhibit_snippet_completions": true, 
  "inhibit_word_completions": true, 
  "log_debug": true, 
  "show_references_in_quick_panel": true
}
```
To modify LSP-gopls settings you can open up the command palette and select `Preference: LSP-gopls Settings` as it is mentioned in the [README](https://github.com/sublimelsp/LSP-gopls).

**Closed by predragnikolic** 2022-08-20 13:17 UTC
