### ISSUE TITLE
Language server xxxx has crashed ,do you want to reatart it

### ISSUE THREAD

**Issue by Guanqing-cool** [sublimelsp/LSP#967] opened 2020-04-13 05:10 UTC
When some language servers open files of corresponding types, a problem window will appear, such as lsp-vue, "language server lsp-vue has crashed, do you want to restart it". After that, the language server cannot be used, and the restart has no effect.
But some language servers can be used normally, such as LSP HTML, LSP CSS, LSP typescript
What causes this?

**Comment by rwols** [comment] 2020-04-13 09:48
Duplicate of https://github.com/sublimelsp/LSP-vue/issues/23

**Closed by rwols** 2020-04-13 09:48 UTC
