### ISSUE TITLE
Language server process not exit after sublime exit

### ISSUE THREAD

**Issue by numbcoder** [sublimelsp/LSP#410] opened 2018-09-12 05:46 UTC
I had used ruby language server solargrah
config:
```json
{
  "clients":
  {
    "solargraph":
    {
      "enabled": true,
      "command": ["solargraph", "stdio"],
      "scopes": ["source.ruby", "source.ruby.rails"],
      "languageId": "ruby",
      "syntaxes": [
        "Packages/Ruby/Ruby.sublime-syntax",
        "Packages/Rails/Ruby on Rails.sublime-syntax",
        "Packages/Rails/HTML (Rails).sublime-syntax"
      ]
    }
  }
}
```
But when I exit Sublime Text editor, the solargraph process not exit, so there will be many solargraph processes if I closed the Sublime and opened it again.

platform: macOS
solargrah version: 0.27.1

Thanks!

**Comment by tomv564** [comment] 2018-09-23 06:28
Looks to be an LSP issue, thanks for reporting!
I believe the solargraph process do get shut down when closing a window, but not when Sublime is exited altogether.

**Comment by olafurpg** [comment] 2018-11-19 18:00
I'm able to reproduce this problem with a Scala language server that I am currently implementing and would like use with Sublime Text.

Steps:
- setup language server in Sublime Text, everything works as expected (thanks for a great plugin!)
- quit Sublime Text, the language server receives a `shutdown` request from the editor client as expected
```json
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "shutdown",
  "params": null
}
```
- the language server does not receive an `exit` notification from the editor client after the `shutdown` request has been responded. I expected to receive the following notification 
```json
{
  "jsonrpc": "2.0",
  "method": "exit",
  "params": null
}
```

In my server implementation I wait for the `exit` notification to kill the process
```scala
  @JsonNotification("exit")
  def exit(): Unit = {
    System.exit(0)
  }
```

Without the notification, I end up with a new zombie process every time Sublime Text is quit.

**Comment by ayoub-benali** [comment] 2018-12-10 07:18
I can confirm that the issue is still there.
@rwols can you re-open the issue or should I create a new one ?

**Comment by tomv564** [comment] 2018-12-10 21:57
Perhaps the same issue as #469 (for which the fix was not yet released?)
Are there any errors visible in the sublime console?

**Comment by ayoub-benali** [comment] 2018-12-11 09:09
I just tested with master branch of LSP still the same issue. Where can I read the console logs?
Since I need to close sublime to trigger the server shutdown I can't see the console content

**Comment by tomv564** [comment] 2018-12-11 21:49
That was an intended change but definitely in the ballpark!
You can run the following statements in the sublime console:
```
from LSP.plugin.core.registry import windows
windows.lookup(sublime.active_window())._handle_window_closed()
```
On my machine, I noticed that the rust language server and LSP don't agree about the validity of the shutdown response - that could be an issue with your server as well?
```
LSP: window 5 closed, ending sessions
LSP: unloading session rls
LSP:  --> shutdown
LSP:      None
LSP: invalid response payload {'id': 2, 'jsonrpc': '2.0', 'result': None}
```

**Comment by ayoub-benali** [comment] 2018-12-11 21:55
```
>>> from LSP.plugin.core.registry import windows
>>> windows.lookup(sublime.active_window())._handle_window_closed()
LSP: window 3 closed, ending sessions
LSP: unloading session metals
LSP:  --> shutdown
LSP: <--  window/logMessage
server: shutting down Metals
LSP:  --> exit
LSP: session metals ended
LSP: clients for window 3 unloaded
```
Which is shutting down the LSP server. The issue then happens when you actually quit sublime

**Comment by rwols** [comment] 2018-12-11 22:36
I have a feeling this is unsolvable with the current ST api. There is no callback that triggers when ST closes.

**Comment by predragnikolic** [comment] 2018-12-11 23:48
There is a workaround, https://forum.sublimetext.com/t/on-close-eventlistener/16113/2 

> There is no way within ST itself to detect when ST is closing.
> You must **spawn another process** that periodically checks whether the ST process is still running.
> FWIW, I don't think on_close gets called when a project is closed either. This is different in that ST does not close if there is another project still open and could potentially ruin your setup.

But it would be much nicer if there was a hook like `plugin_loaded` or `plugin_unloaded`, something like `sublime_closed` or `plugin_terminated` that would notify that sublime is about to be closed.

**Comment by olafurpg** [comment] 2018-12-12 09:04
As @rwols mentions, this issue seems to be caused by Sublime Text and not the LSP package. The shutdown sequence works as expected (`shutdown` request followed by `exit` notification)  when I click on `x` in the Sublime Text window. When I quit Sublime with `Cmd + Q` (macOS) the `shutdown` request is sent but not the `exit` notification.

We can work around this on the language server side by internally calling `exit` after shutdown. Feel free to close this ticket.

**Comment by tomv564** [comment] 2018-12-13 19:41
> We can work around this on the language server side by internally calling exit after shutdown. Feel free to close this ticket.

As an alternative, perhaps the pipe/socket you are talking over is closed, which you may be able to detect?

I'll close the issue now, but remain hopeful we can someday fix this.

**Comment by rwols** [comment] 2020-04-13 09:50
It is solvable now with a new EventListener callback called `on_exit`. It is invoked just before ST exist.

**Comment by rwols** [comment] 2020-05-30 14:16
This will be fixed for ST4.

**Closed by rwols** 2020-05-30 14:16 UTC
Labels: bug, sublime-text-4000
